angular/clutz

src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java
src/test/java/com/google/javascript/cl2dts/type_guard.d.ts
src/test/java/com/google/javascript/cl2dts/type_guard.js

See https://github.com/angular/closure-to-dts/issues/16

Closure pass

---

src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java
src/test/java/com/google/javascript/cl2dts/multi_class.d.ts
src/test/java/com/google/javascript/cl2dts/multi_class.js
src/test/java/com/google/javascript/cl2dts/types.d.ts
src/test/java/com/google/javascript/cl2dts/types.js

Previously this happened to work, because we only tested prototype methods on the default exported class

Generic types

---

src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java
src/test/java/com/google/javascript/cl2dts/enum.d.ts
src/test/java/com/google/javascript/cl2dts/enum_usage.ts

thanks @rkirov for reasoning about the difference between our two boolean conditionals. They should be the same condition, and this exposed a bug.

fix(bug): enums should also be default export

---

src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java
src/test/java/com/google/javascript/cl2dts/type_alias.d.ts
src/test/java/com/google/javascript/cl2dts/type_alias.js
src/test/java/com/google/javascript/cl2dts/type_alias_usage.ts

adds support for type aliases (typedefs in closure).

---

src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java
src/test/java/com/google/javascript/cl2dts/types.d.ts
src/test/java/com/google/javascript/cl2dts/types.js
src/test/java/com/google/javascript/cl2dts/types_usage.ts

fix(types): emit object types

---

src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java
src/test/java/com/google/javascript/cl2dts/types.d.ts
src/test/java/com/google/javascript/cl2dts/types.js

fix(bug): allow nullable parameterized types

---

src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java
src/test/java/com/google/javascript/cl2dts/static_provided.d.ts
src/test/java/com/google/javascript/cl2dts/static_provided.js
src/test/java/com/google/javascript/cl2dts/static_provided_usage.ts

fix(bug): don't print enum declarations as properties

---

src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java
src/test/java/com/google/javascript/cl2dts/provide_single_class.d.ts
src/test/java/com/google/javascript/cl2dts/provide_single_class.js
src/test/java/com/google/javascript/cl2dts/provide_single_class_usage.ts

fix(bug): handle nested classes and enums.

---

src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java
src/test/java/com/google/javascript/cl2dts/types.d.ts
src/test/java/com/google/javascript/cl2dts/types.js

fix(bug): handle untyped object

---

src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java
src/test/java/com/google/javascript/cl2dts/fn_params.js
src/test/java/com/google/javascript/cl2dts/multi_class.js
src/test/java/com/google/javascript/cl2dts/provide_single_class.js

feature(types): don't expose private properties

---

build.gradle
src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java
src/test/java/com/google/javascript/cl2dts/CommandLineInterfaceTest.java
src/test/java/com/google/javascript/cl2dts/ProgramSubject.java

feature(cli): get outfile and externs from command line

---

src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java
src/test/java/com/google/javascript/cl2dts/types.d.ts
src/test/java/com/google/javascript/cl2dts/types.js

also cleanup a duplicated test case
fixes #86

fix(bug): check for name == namespace

---

src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java
src/test/java/com/google/javascript/cl2dts/generics.d.ts
src/test/java/com/google/javascript/cl2dts/generics.js
src/test/java/com/google/javascript/cl2dts/generics_usage.ts

fix(generics): output templatized types for extends.

---

.travis.yml
src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java
src/main/java/com/google/javascript/cl2dts/Depgraph.java
src/test/java/com/google/javascript/cl2dts/DeclarationGeneratorTests.java
src/test/java/com/google/javascript/cl2dts/OptionsTest.java
src/test/java/com/google/javascript/cl2dts/ProgramSubject.java
src/test/java/com/google/javascript/cl2dts/dict.d.ts
src/test/java/com/google/javascript/cl2dts/fn_params.d.ts
src/test/java/com/google/javascript/cl2dts/generics.d.ts
src/test/java/com/google/javascript/cl2dts/lends.d.ts
src/test/java/com/google/javascript/cl2dts/multi_class.d.ts
src/test/java/com/google/javascript/cl2dts/multi_provides.d.ts
src/test/java/com/google/javascript/cl2dts/provide_single_class.d.ts
src/test/java/com/google/javascript/cl2dts/shouldResolveNamedTypes/index.d.ts
src/test/java/com/google/javascript/cl2dts/static_provided.d.ts
src/test/java/com/google/javascript/cl2dts/type_alias.d.ts
src/test/java/com/google/javascript/cl2dts/types.d.ts
src/test/java/com/google/javascript/cl2dts/types_with_externs.d.ts
src/test/java/com/google/javascript/cl2dts/union.d.ts

Fix dependency on set ordering

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/base.js
src/test/java/com/google/javascript/clutz/ctor_func.d.ts
src/test/java/com/google/javascript/clutz/ctor_func.js

feat: support constructor function types.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/main/java/com/google/javascript/clutz/Depgraph.java
src/test/java/com/google/javascript/clutz/OptionsTest.java

- unused parameters
- unused caught exceptions
- switch w/o default case, w/o break

chore: fix a number of Java warings.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/types.d.ts
src/test/java/com/google/javascript/clutz/types.js
src/test/java/com/google/javascript/clutz/types_usage.ts
src/test/java/com/google/javascript/clutz/types_with_externs.d.ts
src/test/java/com/google/javascript/clutz/union.d.ts
src/test/java/com/google/javascript/clutz/union.js

fix: array of functions type is emitted correctly.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/fn_params.d.ts
src/test/java/com/google/javascript/clutz/jsdoc.d.ts
src/test/java/com/google/javascript/clutz/jsdoc.js
src/test/java/com/google/javascript/clutz/nullable.d.ts
src/test/java/com/google/javascript/clutz/types.d.ts

Not only to show off in the demo :-)

feat: emit JSDoc.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/resources/closure.lib.d.ts
src/test/java/com/google/javascript/clutz/private_type.d.ts
src/test/java/com/google/javascript/clutz/private_type.js

Private enums in type positions

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/privates.d.ts
src/test/java/com/google/javascript/clutz/privates.js

Add a test case for private nested classes.

---

src/test/java/com/google/javascript/clutz/provide_single_class.d.ts
src/test/java/com/google/javascript/clutz/provide_single_class.js

Test case for Function typed fields.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/MultiFileTest.java
src/test/java/com/google/javascript/clutz/ProgramSubject.java
src/test/java/com/google/javascript/clutz/googModule/goog_module.d.ts
src/test/java/com/google/javascript/clutz/googModule/goog_module.js
src/test/java/com/google/javascript/clutz/googModule/required.js
src/test/java/com/google/javascript/clutz/googModule/required_module.js

feat: add a test for goo.module.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/resources/third_party_externs.js
src/test/java/com/google/javascript/clutz/types_with_3p_externs.d.ts

fix: do not emit namespaces that collide with static fields in externs.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/type_alias.d.ts
src/test/java/com/google/javascript/clutz/type_alias.js
src/test/java/com/google/javascript/clutz/types_with_3p_externs.d.ts
src/test/java/com/google/javascript/clutz/types_with_3p_externs.js

fix: do not emit any type aliases that shadow ArrayLike.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/types_with_3p_externs.d.ts
src/test/java/com/google/javascript/clutz/types_with_3p_externs.js

fix: do not add _instance for platform externs

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/private_type.d.ts
src/test/java/com/google/javascript/clutz/private_type.js

fix: add a missing private enum case.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/resources/closure.lib.d.ts
src/test/java/com/google/javascript/clutz/private_class.d.ts
src/test/java/com/google/javascript/clutz/private_class.js

We already emit PrivateType, but for extend/implement positions an
actual class/interface is needed.
Closes #191

fix: introduce PrivateInterface and PrivateClass

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java

This is more of a temporary fix. A better solution will follow when we tackle #205.

fix: restrict the platform externs list down.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/ProgramSubject.java
src/test/java/com/google/javascript/clutz/record.d.ts
src/test/java/com/google/javascript/clutz/record.externs.js
src/test/java/com/google/javascript/clutz/record.js
src/test/java/com/google/javascript/clutz/record_usage.ts

adds support for @record type.

adds test for @record type.

---

build.gradle
src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/types_externs_with_platform.d.ts
src/test/java/com/google/javascript/clutz/types_externs_with_platform.js
src/test/java/com/google/javascript/clutz/types_externs_with_platform_usage.ts

Remove work-arounds for supporting upstream closure compiler.

Upgrade closure to current release.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/types.d.ts
src/test/java/com/google/javascript/clutz/types.js
src/test/java/com/google/javascript/clutz/types_externs_with_platform.d.ts

In typescript the optionality is handled in the name of the property by
adding ? to the name, vs closures approach to keep it purely as a type
of T | undefined.
Closes #232

support optional props in record types.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/DeclarationGeneratorTests.java
src/test/java/com/google/javascript/clutz/general_with_platform.d.ts
src/test/java/com/google/javascript/clutz/types_externs_with_platform.d.ts
src/test/java/com/google/javascript/clutz/types_externs_with_platform.externs.js

Adds an extra file general_with_platform.d.ts which will contain all
expected output from the platfrom externs.

tighten what is considered a platform extern.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/reserved_var_names.d.ts
src/test/java/com/google/javascript/clutz/reserved_var_names.js
src/test/java/com/google/javascript/clutz/reserved_var_names_usage.ts

Handle reserved words gracefully.

---

src/main/java/com/google/javascript/gents/ClassConversionPass.java
src/test/java/com/google/javascript/gents/singleTests/classes.js
src/test/java/com/google/javascript/gents/singleTests/classes.ts

Es6 method short hand

---

src/main/java/com/google/javascript/gents/TypeScriptGenerator.java

Use local clang format.

---

src/main/java/com/google/javascript/gents/CommentLinkingPass.java
src/test/java/com/google/javascript/gents/singleTests/comments.js
src/test/java/com/google/javascript/gents/singleTests/comments.ts

strip type annotations from @export

---

src/main/java/com/google/javascript/gents/Options.java
src/main/java/com/google/javascript/gents/TypeAnnotationPass.java
src/main/java/com/google/javascript/gents/TypeScriptGenerator.java
src/test/java/com/google/javascript/gents/OptionsTest.java
src/test/java/com/google/javascript/gents/TypeScriptGeneratorMultiTests.java
src/test/java/com/google/javascript/gents/TypeScriptGeneratorTests.java
src/test/java/com/google/javascript/gents/singleTests/externs_map.js
src/test/java/com/google/javascript/gents/singleTests/externs_map.ts
src/test/java/com/google/javascript/gents/test_externs_map.json

gents now allows the user to pass a json file with an extern/typing map
for the cases where there are spelling differences between the two.
fixes #336

gents accepts a json file with an extern -> type mapping

---

src/main/java/com/google/javascript/gents/CollectModuleMetadata.java
src/main/java/com/google/javascript/gents/ModuleConversionPass.java
src/main/java/com/google/javascript/gents/NameUtil.java
src/main/java/com/google/javascript/gents/TypeAnnotationPass.java
src/main/java/com/google/javascript/gents/TypeConversionPass.java
src/test/java/com/google/javascript/gents/singleTests/typedef.js
src/test/java/com/google/javascript/gents/singleTests/typedef.ts
src/test/java/com/google/javascript/gents/singleTests/typedef_export.js
src/test/java/com/google/javascript/gents/singleTests/typedef_export.ts

This is based on the interfaces pull request. Please only review the later two commits in here.
This pull request was brought to you by LH102 FRA --> MUC.

feat: support typedefs

---

src/main/java/com/google/javascript/gents/TypeConversionPass.java
src/test/java/com/google/javascript/gents/singleTests/fields.js
src/test/java/com/google/javascript/gents/singleTests/fields.ts

this.foo.bar = 5 no longer creates a class field bar = 5
fixes #357

Do not promote dotted member assigments to fields

---

src/main/java/com/google/javascript/gents/GentsCodeGenerator.java
src/test/java/com/google/javascript/gents/singleTests/access_modifiers.ts
src/test/java/com/google/javascript/gents/singleTests/classes.js
src/test/java/com/google/javascript/gents/singleTests/classes.ts
src/test/java/com/google/javascript/gents/singleTests/fields.ts
src/test/java/com/google/javascript/gents/singleTests/module_class.ts
src/test/java/com/google/javascript/gents/singleTests/proto_methods.ts
src/test/java/com/google/javascript/gents/singleTests/static_methods.ts

Summary:
Adds an empty line between functions in a class.

feat: add empty lines between methods in classes.

---

DEVELOPER.md
package.json

Add rudimentary developer documentation.

---

src/main/java/com/google/javascript/gents/StyleFixPass.java
src/test/java/com/google/javascript/gents/singleTests/functions.js
src/test/java/com/google/javascript/gents/singleTests/functions.ts

fix: Don't try to rewrite arrow functions in gents

---

src/main/java/com/google/javascript/gents/RemoveGoogScopePass.java
src/test/java/com/google/javascript/gents/singleTests/goog_provide.js
src/test/java/com/google/javascript/gents/singleTests/goog_provide.ts
src/test/java/com/google/javascript/gents/singleTests/goog_scope.js
src/test/java/com/google/javascript/gents/singleTests/goog_scope.ts

Fixes #401 
This change was brought to you by WN2175 from SJC --> SNA.

fix: NPE in RemoveGoogScopePass when calling functions on an imported function

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java

Encountered an UnionType being cast as an ObjectType.

Fix ClassCastException.

---

src/main/java/com/google/javascript/gents/ModuleConversionPass.java
src/main/java/com/google/javascript/gents/NodeComments.java
src/test/java/com/google/javascript/gents/singleTests/goog_provide.js
src/test/java/com/google/javascript/gents/singleTests/goog_provide.ts
src/test/java/com/google/javascript/gents/singleTests/module_class2.js
src/test/java/com/google/javascript/gents/singleTests/module_class2.ts

fix: Don't drop @fileoverview comments

---

src/main/java/com/google/javascript/gents/TypeConversionPass.java
src/test/java/com/google/javascript/gents/singleTests/fields.js
src/test/java/com/google/javascript/gents/singleTests/fields.ts

Anonymous functions have no name and were causing an exception when we
tried to get it.
Fixes #418

Fixes exception with anonymous functions and field extraction

---

src/main/java/com/google/javascript/gents/TypeConversionPass.java
src/test/java/com/google/javascript/gents/singleTests/parameter_prop.js
src/test/java/com/google/javascript/gents/singleTests/parameter_prop.ts

Allow fields with inferred types to be parameter properties.

---

build.gradle
src/test/java/com/google/javascript/clutz/DepgraphTest.java
src/test/java/com/google/javascript/clutz/ProgramSubject.java

These reflect the latest versions available both externally and internally.

Upgrade external dependencies to more recent versions.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java

This is preferred style, as it communicates intent more clearly.

cleanup: explicit immutable type for CONST_CASE decl

---

src/main/java/com/google/javascript/gents/GentsCodeGenerator.java
src/main/java/com/google/javascript/gents/TypeAnnotationPass.java
src/test/java/com/google/javascript/gents/singleTests/object_map.js
src/test/java/com/google/javascript/gents/singleTests/object_map.ts

Fix https://github.com/angular/clutz/issues/390
@rkirov PTAL

Convert Closure Object map type to TS properly

---

src/test/java/com/google/javascript/clutz/DeclarationSyntaxTest.java

AFAIK we're on JDK 8?
btw I'm trying to generalize this file to gents so we can compile `.ts`

Use `.destroyForcibly`

---

src/test/java/com/google/javascript/gents/singleTests/externs_map.d.ts
src/test/java/com/google/javascript/gents/singleTests/fields.js
src/test/java/com/google/javascript/gents/singleTests/fields.ts
src/test/java/com/google/javascript/gents/singleTests/goog_provide.js
src/test/java/com/google/javascript/gents/singleTests/goog_provide.ts
src/test/java/com/google/javascript/gents/singleTests/interface.js
src/test/java/com/google/javascript/gents/singleTests/interface.ts
src/test/java/com/google/javascript/gents/singleTests/parameter_prop.js
src/test/java/com/google/javascript/gents/singleTests/parameter_prop.ts
src/test/java/com/google/javascript/gents/singleTests/undeclared_property.d.ts

Prepare for https://github.com/angular/clutz/issues/404

fix(gents): PR2/2 Fix some gents tests so output can compile.

---

src/test/java/com/google/javascript/gents/singleTests/casts.js
src/test/java/com/google/javascript/gents/singleTests/casts.ts
src/test/java/com/google/javascript/gents/singleTests/comments.js
src/test/java/com/google/javascript/gents/singleTests/comments.ts
src/test/java/com/google/javascript/gents/singleTests/export_rewrite.js
src/test/java/com/google/javascript/gents/singleTests/export_rewrite.ts
src/test/java/com/google/javascript/gents/singleTests/plain_destructure.js
src/test/java/com/google/javascript/gents/singleTests/plain_destructure.ts
src/test/java/com/google/javascript/gents/singleTests/typedef_export.js
src/test/java/com/google/javascript/gents/singleTests/typedef_export.ts

Prepare for https://github.com/angular/clutz/issues/404

fix(gents): PR1/2 Fix some gents tests so inputs and outputs can actually compile.

---

src/test/java/com/google/javascript/clutz/DeclarationGeneratorTests.java
src/test/java/com/google/javascript/clutz/DeclarationSyntaxTest.java
src/test/java/com/google/javascript/gents/GeneratedSyntaxTest.java
src/test/java/com/google/javascript/gents/singleTests/destr.js
src/test/java/com/google/javascript/gents/singleTests/destr.ts
src/test/java/com/google/javascript/gents/singleTests/functions.js
src/test/java/com/google/javascript/gents/singleTests/functions.ts

Last piece of https://github.com/angular/clutz/issues/404
Depends on https://github.com/angular/clutz/pull/476 and https://github.com/angular/clutz/pull/486

Add a test to verify that we generate valid .ts code

---

src/test/java/com/google/javascript/clutz/nested_typedef_module.d.ts
src/test/java/com/google/javascript/clutz/nested_typedef_module.js
src/test/java/com/google/javascript/clutz/nested_typedef_module_usage.ts

Add a test for inner typedef inside a goog.module.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java

In preparation for using options.setAssumeForwardDeclations(true),
one has to make sure that compiler.getTypeRegistry is never called
before compiler.compile(...,...,options). Otherwise, an internal
state is incorrectly built that uses the wrong value for
forwardDeclaredTypes.

Move access to .getTypeRegistry after .compile.

---

src/main/java/com/google/javascript/clutz/Options.java
src/test/java/com/google/javascript/clutz/async_await_with_platform.d.ts
src/test/java/com/google/javascript/clutz/async_await_with_platform.js

Adds a test for async/await code.

Switch to accepting ECMASCRIPT_NEXT

---

build.gradle
src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/general_with_platform.d.ts

Minor changes need to platform externs generated .d.ts.

Upgrade closure to v20170806.

---

src/main/java/com/google/javascript/gents/ModuleConversionPass.java
src/test/java/com/google/javascript/gents/multiTests/jslib_imports/destructuring_imports.js
src/test/java/com/google/javascript/gents/multiTests/jslib_imports/destructuring_imports.ts
src/test/java/com/google/javascript/gents/multiTests/jslib_imports/export_module_both_keep.js
src/test/java/com/google/javascript/gents/multiTests/jslib_imports/import_module.js
src/test/java/com/google/javascript/gents/multiTests/jslib_imports/import_module.ts

Fixes https://github.com/angular/clutz/issues/537

Handles destructuring imports in clutz generated .d.ts

---

src/main/java/com/google/javascript/gents/ModuleConversionPass.java
src/test/java/com/google/javascript/gents/multiTests/converts_ts_module_require/a/b/c/deep_keep.es5.js
src/test/java/com/google/javascript/gents/multiTests/converts_ts_module_require/converts_ts_module_require.js
src/test/java/com/google/javascript/gents/multiTests/converts_ts_module_require/converts_ts_module_require.ts
src/test/java/com/google/javascript/gents/multiTests/jslib_imports/export_module_no_default_exports_keep.js
src/test/java/com/google/javascript/gents/multiTests/jslib_imports/multiple_destructing_imports.js
src/test/java/com/google/javascript/gents/multiTests/jslib_imports/multiple_destructing_imports.ts

Fixes https://github.com/angular/clutz/issues/392
Fixes https://github.com/angular/clutz/issues/573

supports multiple destructured imports

---

build.gradle
src/main/java/com/google/javascript/clutz/InitialParseRetainingCompiler.java

Add an additional @Override, that was printing a warning.

Upgrade closure to v20171203.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java

Some bad formatting slipped in while Travis was down.

Re-format clutz code.

---

src/test/java/com/google/javascript/clutz/partial/type_union.d.ts
src/test/java/com/google/javascript/clutz/partial/type_union.js

Add a test to confirm that the closure fix for unresolved type union works in clutz.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/partial/enum_alias.d.ts
src/test/java/com/google/javascript/clutz/partial/enum_alias.js

Fix for enum aliasing unknown enums.

---

src/main/java/com/google/javascript/clutz/ImportRenameMapBuilder.java
src/test/java/com/google/javascript/clutz/partial/separated_destructure.d.ts
src/test/java/com/google/javascript/clutz/partial/separated_destructure.js

Support destructuring goog.require() variables on a subsequent line.

---

build.gradle
src/test/java/com/google/javascript/clutz/ProgramSubject.java

This is the most recent release of truth, which made some API changes.

update version of truth to 0.39

---

src/main/java/com/google/javascript/clutz/AliasMapBuilder.java
src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/partial/import_without_reexport.d.ts
src/test/java/com/google/javascript/clutz/partial/import_without_reexport.js

Ran some tests in g3, and discovered I needed a better conditional.

Make sure the symbol is unknown type before assuming its an alias.

---

src/test/java/com/google/javascript/clutz/general_with_platform.d.ts
src/test/java/com/google/javascript/clutz/generator_with_platform.d.ts
src/test/java/com/google/javascript/clutz/partial/generator_partial.d.ts

One new class was added to externs and IteratorIterable is inferred
correctly now.

Support new closure nightly.

---

build.gradle
src/test/java/com/google/javascript/clutz/ProgramSubject.java

Upstreaming from an internal clean up to Truth library usage.

Upgrade to Truth 0.40 library.

---

src/main/java/com/google/javascript/gents/TypeConversionPass.java
src/test/java/com/google/javascript/gents/singleTests/enum.js
src/test/java/com/google/javascript/gents/singleTests/enum.ts

Fixes https://github.com/angular/clutz/issues/653

Preserve comments in enum.

---

src/main/java/com/google/javascript/gents/CommentLinkingPass.java
src/main/java/com/google/javascript/gents/TypeConversionPass.java
src/test/java/com/google/javascript/gents/singleTests/typedef.js
src/test/java/com/google/javascript/gents/singleTests/typedef.ts

Fixes https://github.com/angular/clutz/issues/654

Preserve comments on typedefs.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/inferred_obj.d.ts
src/test/java/com/google/javascript/clutz/inferred_obj.js
src/test/java/com/google/javascript/clutz/invalid_names.d.ts

Emit warnings when skipping props and vars with // not //!! so that
tests can be written against them.

When emitting an obj lit type quote props when needed.

---

src/main/java/com/google/javascript/gents/Options.java

This change has already been made internally.

Set gents closure input flag to ES_NEXT

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java

For some reason, I cannot reproduce the issue in our test harness, but
for internal Google users, when compiling over the standard typings
clutz emits:
declare namespace o_O.clutz.this {
...
}
This is invalid TS syntactically.
Previously we fixed a similar issue with
https://github.com/angular/clutz/commit/5df4937a262580fff8cfac05729027d8b157a9d1.
but we missed this instance.

Use both 'this.' and 'window.' for normalization of repeated global symbols

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/enum.d.ts
src/test/java/com/google/javascript/clutz/enum.js

Try to emit literal type as much as possible.

Improve Clutz string enums translation

---

DEVELOPER.md
README.md

We only really care to test against closure at HEAD, because that is
where our main user is.
Also move some developer docs into DEVELOPER.md.

document our versioning strategy

---

src/main/java/com/google/javascript/clutz/Options.java
src/test/java/com/google/javascript/clutz/general_with_platform.d.ts

Also, update goldens for a new interface in externs.

Upstream dependency management flags changes.

---

src/test/java/com/google/javascript/clutz/ClosureEnvTest.java
src/test/java/com/google/javascript/clutz/env/browser.js

Add tests for --closure_env

---

src/test/java/com/google/javascript/gents/GeneratedSyntaxTest.java
src/test/java/com/google/javascript/gents/OptionsTest.java
src/test/java/com/google/javascript/gents/TypeScriptGeneratorTests.java

Also found some tests that were shadowed by the golden generation and
never ran.
All of those fail, and do not seem to add anything more than what
goldens already test, so I removed them.
Finally, some JUnit annotations were added as they are needed for the
blaze testing setup.

Add support for SOURCE_ROOT for gents tests.

---

npm-shrinkwrap.json
package.json

`TYPESCRIPT_LIB_D_TS` has not been updated.

Update TypeScript to latest v3.3

---

README.md

This adds a comment to README on where to look for ./gradelew

Added instruction to readme

---

src/main/java/com/google/javascript/clutz/ImportBasedMapBuilder.java
src/main/java/com/google/javascript/clutz/ImportRenameMapBuilder.java
src/test/java/com/google/javascript/clutz/partial/requireType.d.ts
src/test/java/com/google/javascript/clutz/partial/requireType.js

goog.requireType is a new addition to the Closure module system.

Handle goog.requireType identically to goog.require.

---

src/main/java/com/google/javascript/gents/CommentLinkingPass.java
src/test/java/com/google/javascript/gents/multiTests/import_rewrite/export.js
src/test/java/com/google/javascript/gents/multiTests/import_rewrite/export.ts
src/test/java/com/google/javascript/gents/multiTests/import_rewrite/import.js
src/test/java/com/google/javascript/gents/multiTests/import_rewrite/import.ts
src/test/java/com/google/javascript/gents/multiTests/import_rewrite/log.json

These are no longer useful with import statements.

Remove @suppress {extraRequire} JsDoc comments.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/abstract_class.d.ts
src/test/java/com/google/javascript/clutz/abstract_class.js

TGP looks good (after some cleanups).

Support `@abstract` in Clutz.

---

src/main/java/com/google/javascript/gents/ModuleConversionPass.java
src/test/java/com/google/javascript/gents/multiTests/exported_default_obj/exporter.js
src/test/java/com/google/javascript/gents/multiTests/exported_default_obj/exporter.ts
src/test/java/com/google/javascript/gents/multiTests/exported_default_obj/importer.js
src/test/java/com/google/javascript/gents/multiTests/exported_default_obj/importer.ts

They are threated equivalently with goog.require.

Add support for goog.requireType and goog.forwardDeclare to gents.

---

build.gradle
src/test/java/com/google/javascript/clutz/ProgramSubject.java

Subject type is no longer generic.

Upgrade google.truth library to 1.0

---

src/test/java/com/google/javascript/clutz/testdata/general_with_platform.d.ts

These are new externs from JSCompiler upstream.

add new types to rebaseline tests
