angular/clutz

src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java
src/test/java/com/google/javascript/cl2dts/DeclarationGeneratorTests.java
src/test/java/com/google/javascript/cl2dts/ProgramSubject.java
src/test/java/com/google/javascript/cl2dts/types_with_externs.d.ts
src/test/java/com/google/javascript/cl2dts/types_with_externs.js
src/test/java/com/google/javascript/cl2dts/types_with_externs_usage.ts

fixes attaching Object.prototype methods to object literal types when
externs are present.
Closes #18

add support for tests with externs

---

src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java
src/test/java/com/google/javascript/cl2dts/interface.d.ts
src/test/java/com/google/javascript/cl2dts/interface.js
src/test/java/com/google/javascript/cl2dts/interface_usage.ts

We emit the static methods and variable in a namespace, instead of a var
union type, as done previously. That way we do not interfere with any
enums being output.
Closes #78

fix(interface): statics on interfaces emitted in a namespace.

---

src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java
src/test/java/com/google/javascript/cl2dts/types_with_externs.d.ts
src/test/java/com/google/javascript/cl2dts/types_with_externs.js

They are still present for TS users, but provided by lib.d.ts.
Closes #76

do not emit static apply and call on functions.

---

build.gradle
src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java
src/test/java/com/google/javascript/cl2dts/types_with_externs.d.ts
src/test/java/com/google/javascript/cl2dts/types_with_externs.js
src/test/java/com/google/javascript/cl2dts/types_with_externs_usage.ts

Platform apis like Arguments and Nodelist need to be translated to
their corresponding apis in lib.d.ts
Upgrade closure to the newest released version.

Add support for Arguments and NodeList.

---

src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java
src/test/java/com/google/javascript/cl2dts/lends.d.ts
src/test/java/com/google/javascript/cl2dts/lends.js
src/test/java/com/google/javascript/cl2dts/lends_usage.ts
src/test/java/com/google/javascript/cl2dts/provide_single_class.d.ts
src/test/java/com/google/javascript/cl2dts/provide_single_class.js

It appears that @lends has a way to create duplicate fields.
Adds a verification that deduping is not needed if prototype fields
are just added (without @lends), but conservatively we always do
deduping.

fix dedups fields from prototype chain.

---

src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java
src/test/java/com/google/javascript/cl2dts/provide_single_class.js

Previously we were checking the visibility of the property type, but
the correct check uses the jsdoc of the property itself.

fix: do not output private properties.

---

src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java
src/test/java/com/google/javascript/cl2dts/types_with_externs.d.ts
src/test/java/com/google/javascript/cl2dts/types_with_externs.js

Previous attempts to fix this missed the fact that externs need to be
present to reproduce the bug.

fix: Function type vars should not output as classes.

---

src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java
src/resources/closure.lib.d.ts
src/test/java/com/google/javascript/cl2dts/DeclarationSyntaxTest.java
src/test/java/com/google/javascript/cl2dts/types_with_externs.d.ts
src/test/java/com/google/javascript/cl2dts/types_with_externs.js
src/test/java/com/google/javascript/cl2dts/types_with_externs_usage.ts

Introduces an auxillary .d.ts `closure.lib.d.ts` that needs to be
passed into all consumers of cl2dts.
Closes #81

fix: local Error class extending global Error class.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/empty_type_args.d.ts
src/test/java/com/google/javascript/clutz/empty_type_args.js

In Closure, types that filled all template args from a super type are
still represented by a templatized type.
Fixes #123.

fix: do not emit empty templatized args.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/base.js
src/test/java/com/google/javascript/clutz/ctor_func.d.ts
src/test/java/com/google/javascript/clutz/ctor_func.js
src/test/java/com/google/javascript/clutz/static_inheritance_mismatch.d.ts
src/test/java/com/google/javascript/clutz/static_inheritance_mismatch.js

In TypeScript, the "static" side of classes must correctly inherit from
any of its parents. In Closure, the methods are completely separate and
do not have to match. To paper over the difference, emit overloads so
that TypeScript allows the inheritance.
This pretends functions exist that do not, and it will fail for
functions that only differ in return type, but it should be good enough
for most code, for now.
Fixes #120.

feat: mismatched inherited static properties.

---

src/main/java/com/google/javascript/clutz/Constants.java
src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/main/java/com/google/javascript/clutz/DeclarationGeneratorException.java
src/main/java/com/google/javascript/clutz/Options.java
src/test/java/com/google/javascript/clutz/DeclarationGeneratorTests.java
src/test/java/com/google/javascript/clutz/ErrorHandlingTest.java
src/test/java/com/google/javascript/clutz/MultiFileTest.java
src/test/java/com/google/javascript/clutz/ProgramSubject.java
src/test/java/com/google/javascript/clutz/refer_from_default_ns.js

- print nicer messages when run from the command line, no stack traces
by default.
- use JSCompiler's error management framework. It's generally sound and
exposes the structures we need. Just the error manager/error handler
system is a bit odd.
- collect all errors that occur during a translation, don't bail on the
first one.
- track error locations. This is not entirely exact as it tracks the
containing symbol's location in walk(), not the property's location,
but it's better than nothing.
- Move the disapproval namespace into a different file as it slightly
screws up font rendering in Eclipse for me (yeah, I know).
- add tests for error handling. For the time being, this seems simpler
than extending the .js/.d.ts format.
- extend Program to allow compiling from strings again
- extend …

Improve error handling.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/provide_single_class.d.ts
src/test/java/com/google/javascript/clutz/provide_single_class.js
src/test/java/com/google/javascript/clutz/provide_single_class_usage.ts
src/test/java/com/google/javascript/clutz/static_provided.d.ts
src/test/java/com/google/javascript/clutz/static_provided.js
src/test/java/com/google/javascript/clutz/static_provided_usage.ts

Previously, we expected an explicit goog.provide for inner classes,
enums and interfaces, but according to style guide such requirers are
forbidden.
Now we do a second pass over the properties of default exported classes
and emit the inner properties that are not static methods or fields into
a namespace.

fix: inner classes, enums and interfaces are emitted.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/resources/third_party_externs.js
src/test/java/com/google/javascript/clutz/ProgramSubject.java
src/test/java/com/google/javascript/clutz/types_with_externs.d.ts
src/test/java/com/google/javascript/clutz/types_with_externs.js

skip platform based externs as they might mirror types in lib.d.ts.

emit namespaces for top-level extern symbols.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/ctor_func.d.ts
src/test/java/com/google/javascript/clutz/dict.d.ts
src/test/java/com/google/javascript/clutz/empty_type_args.d.ts
src/test/java/com/google/javascript/clutz/fn_params.js
src/test/java/com/google/javascript/clutz/forward_declare.d.ts
src/test/java/com/google/javascript/clutz/generics.d.ts
src/test/java/com/google/javascript/clutz/goog_require.d.ts
src/test/java/com/google/javascript/clutz/lends.d.ts
src/test/java/com/google/javascript/clutz/multi_class.d.ts
src/test/java/com/google/javascript/clutz/multi_class.js
src/test/java/com/google/javascript/clutz/multi_provides.d.ts
src/test/java/com/google/javascript/clutz/privates.d.ts
src/test/java/com/google/javascript/clutz/privates.js
src/test/java/com/google/javascript/clutz/provide_single_class.d.ts
src/test/java/com/google/javascript/clutz/provide_single_class.js
src/test/java/com/google/javascript/clutz/refer_from_default_ns.d.ts
src/test/java/com/google/javascript/clutz/shouldPruneProvidesFromNonrootFile/require.d.ts
src/test/java/com/google/javascript/clutz/shouldResolveNamedTypes/index.d.ts
src/test/java/com/google/javascript/clutz/static_inheritance_mismatch.d.ts
src/test/java/com/google/javascript/clutz/static_provided.d.ts
src/test/java/com/google/javascript/clutz/types_with_externs.d.ts

When a type has private fields, add special fields called
`private no(ClassSide)?StructuralTyping_: any;` to avoid accidentally
applying structural typing to a type that does not support that.
Also move all tests for `@private` annotations into their own file, so later
maintainers have a chance to find that code.

feat: prevent structural typing w/ private fields.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/static_inheritance_mismatch.d.ts
src/test/java/com/google/javascript/clutz/static_inheritance_mismatch.js

Instead of throwing errors, we skip over if one (or all) of the
overlapping definitions are private. Also we support overloading when
the types are compatible.

emitting static overloads skips over private and compatible fields.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/aliased_enums.d.ts
src/test/java/com/google/javascript/clutz/ctor_func.d.ts
src/test/java/com/google/javascript/clutz/empty_type_args.d.ts
src/test/java/com/google/javascript/clutz/enum.d.ts
src/test/java/com/google/javascript/clutz/generics.d.ts
src/test/java/com/google/javascript/clutz/interface.d.ts
src/test/java/com/google/javascript/clutz/multi_class.d.ts
src/test/java/com/google/javascript/clutz/provide_single_class.d.ts
src/test/java/com/google/javascript/clutz/refer_from_default_ns.d.ts
src/test/java/com/google/javascript/clutz/shouldResolveNamedTypes/index.d.ts
src/test/java/com/google/javascript/clutz/static_inheritance_mismatch.d.ts
src/test/java/com/google/javascript/clutz/static_provided.d.ts
src/test/java/com/google/javascript/clutz/types_with_externs.d.ts

This makes it much less likely that a type or package gets shadowed by another
type or package with the same name somewhere in the namespace hierarchy.
There is a remaining corner case around re-declared global names like `Element`
or `Object`. The fix would be to alias *all* global names, but that risks
aliasing global names from Closure that do not exist in TypeScript.
Fixes #144.

fix: always generate absolute names.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/null_type.d.ts
src/test/java/com/google/javascript/clutz/null_type.js

Union types can end up having no legal branch, e.g. with `null=`. Emit an `any`
type for those cases - `any` is TypeScript's closest representation for a
Null Type / Bottom Type.
Fixes #141.

fix: handle empty union types.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/resources/closure.lib.d.ts
src/test/java/com/google/javascript/clutz/private_type.d.ts
src/test/java/com/google/javascript/clutz/private_type.js

Surprisingly, Closure allows private types to be used in public APIs.
Emit an empty object type literal for them, i.e. a type that allows no
use but being passed around and is incompatible with everything else.
Fixes #140.

feat: handle private types in public APIs.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/aliased_enum_usage.ts
src/test/java/com/google/javascript/clutz/aliased_enums.d.ts
src/test/java/com/google/javascript/clutz/aliased_enums.js
src/test/java/com/google/javascript/clutz/enum.d.ts
src/test/java/com/google/javascript/clutz/interface.d.ts
src/test/java/com/google/javascript/clutz/provide_single_class.d.ts
src/test/java/com/google/javascript/clutz/static_provided.d.ts

Enum names are the names of the symbol they get assigned to, not the
names of the underlying type they refer to.
Fixes #139.

feat: support renaming aliased enums.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/undefined_provide.d.ts
src/test/java/com/google/javascript/clutz/undefined_provide.js

This is sometimes used just for the require/provide markers, e.g. to support
AutoJsDeps.

feat: support files that provide non-defined symbols.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/resources/third_party_externs.js
src/test/java/com/google/javascript/clutz/types_with_externs.d.ts

Changed the extern strategy to go over all symbols and emit ones that
are not covered by the preceeding namespace.
Some tricky edge cases with typedefs acting as namespaces.

fix broken polymer externs output.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/main/java/com/google/javascript/clutz/DeclarationGeneratorException.java
src/test/java/com/google/javascript/clutz/ErrorHandlingTest.java
src/test/java/com/google/javascript/clutz/ProgramSubject.java

The new ones contain source snippets pointing at the incorrect sources,
and no longer have "(unknown)" placeholders for absent sources.
They also contain shell colour codes.
Fixes #162.

feat: use ErrorFormat to generate nicer error messages.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/resources/third_party_externs.js
src/test/java/com/google/javascript/clutz/types_with_3p_externs.d.ts
src/test/java/com/google/javascript/clutz/types_with_3p_externs.js

Closure APIs do not provide a method to check for namespaces, so we use
the presence of Object type as a heuristic.

support nested namespaces in externs.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/static_inheritance_mismatch_nested_type.d.ts
src/test/java/com/google/javascript/clutz/static_inheritance_mismatch_nested_type.js

Nested types need to correctly inherit the "class static side" in TS.
Closure code however commonly re-defines incompatible enums in
subclasses, leading to TS side errors.
This change only fixes the problem for enums. It's unclear if we can
fix it for inherited `class`es, as that'd mean overloading a class ctor
function. However it turns out enums are the only common issue in the
actual, real world Closure code base.
Semi-fixes #154.

feat: handle nested enum type name collisions.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/untyped_provide.d.ts
src/test/java/com/google/javascript/clutz/untyped_provide.js

Surprisingly, these behave differently from undefined provides, in that there
is no symbol at all for the provide (even though it is assigned!). Just emit
an empty namespace.
Fixes #172 for the immediate issue, but still would need to export the actual type shape at some point.

feat: support untyped provides.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/interface.d.ts
src/test/java/com/google/javascript/clutz/interface.js

Interfaces containing static properties can simply be treated like
namespaces with no default export (`isDefault == false`).
Fixes #179.

feat: simplify & fix interface walking.

---

src/main/java/com/google/javascript/clutz/Options.java
src/test/java/com/google/javascript/clutz/MultiFileTest.java
src/test/java/com/google/javascript/clutz/ProgramSubject.java
src/test/java/com/google/javascript/clutz/abstract_method.js
src/test/java/com/google/javascript/clutz/shouldWorkWithOutOfOrderProvides/dep.js
src/test/java/com/google/javascript/clutz/shouldWorkWithOutOfOrderProvides/index.d.ts
src/test/java/com/google/javascript/clutz/shouldWorkWithOutOfOrderProvides/index.js

JS compiler complains about late provides, but still emits correct type
information, so we turn off that check.
Fixes bug in error-checking on all unit tests (wrong assertion), and a
few js code changes that were necessitated by that.

do not throw on out-of-order sources.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/ClutzErrorManagerTest.java
src/test/java/com/google/javascript/clutz/abstract_method.d.ts
src/test/java/com/google/javascript/clutz/ctor_func.d.ts
src/test/java/com/google/javascript/clutz/dict.d.ts
src/test/java/com/google/javascript/clutz/empty_type_args.d.ts
src/test/java/com/google/javascript/clutz/forward_declare.d.ts
src/test/java/com/google/javascript/clutz/generics.d.ts
src/test/java/com/google/javascript/clutz/goog_require.d.ts
src/test/java/com/google/javascript/clutz/inner_typedef.d.ts
src/test/java/com/google/javascript/clutz/interface.d.ts
src/test/java/com/google/javascript/clutz/jsdoc.d.ts
src/test/java/com/google/javascript/clutz/lends.d.ts
src/test/java/com/google/javascript/clutz/multi_class.d.ts
src/test/java/com/google/javascript/clutz/multi_provides.d.ts
src/test/java/com/google/javascript/clutz/privates.d.ts
src/test/java/com/google/javascript/clutz/provide_instance.d.ts
src/test/java/com/google/javascript/clutz/provide_single_class.d.ts
src/test/java/com/google/javascript/clutz/refer_from_default_ns.d.ts
src/test/java/com/google/javascript/clutz/shouldPruneProvidesFromNonrootFile/require.d.ts
src/test/java/com/google/javascript/clutz/shouldResolveNamedTypes/index.d.ts
src/test/java/com/google/javascript/clutz/shouldWorkWithOutOfOrderProvides/index.d.ts
src/test/java/com/google/javascript/clutz/static_inheritance_mismatch.d.ts
src/test/java/com/google/javascript/clutz/static_inheritance_mismatch_nested_type.d.ts
src/test/java/com/google/javascript/clutz/static_provided.d.ts
src/test/java/com/google/javascript/clutz/types_with_3p_externs.d.ts

This fixes all sorts of static overwrite issues and removes a number of
cludgy solutions (like intersection types on enums, overloading function
declarations).
Closes #184

Emit class A (statics) and class A_Instance per closure class A.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/MultiFileTest.java
src/test/java/com/google/javascript/clutz/googModule/goog_module.d.ts
src/test/java/com/google/javascript/clutz/googModule/goog_module.js
src/test/java/com/google/javascript/clutz/googModule/required_module_default.js

Since default export does not have a fixed symbol name at the export
site, Closure introduces synthetic $jscomp namespace, which needs to be
cleaned-up before emitting.
Closes #186

feat: fix goog.module with default export.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/prototype_inferred_type.d.ts
src/test/java/com/google/javascript/clutz/prototype_inferred_type.js

This can happen very rarely (Foo.prototype is not a valid type symbol in
Closure either), but jquery externs manages to produce it by
setting:
jQuery.fn = jQuery.prototype.
Closes #206

fix: do not emit .prototype as a type.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/resources/third_party_externs.js
src/test/java/com/google/javascript/clutz/types_with_3p_externs.d.ts

Private default provides are not common, but when going through externs
we output each class and interface as a default provide.

fix: skip emitting private default provides.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/private_provided_single_class.d.ts
src/test/java/com/google/javascript/clutz/private_provided_single_class.js
src/test/java/com/google/javascript/clutz/types_with_3p_externs.d.ts

Second attempt, completely skipping the value, results in broken code.
Instead emit a field of PrivateType.

fix: default exported private values.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/extends_function_with_platform.d.ts
src/test/java/com/google/javascript/clutz/extends_function_with_platform.js

Handle a todo to separate the generic type visitor (used for var a:
<...> type positions), from the extends/implements type visitor (used
for class A extends <...> type positions).

fix: emit correct code for classes extending Function.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/DeclarationSyntaxTest.java
src/test/java/com/google/javascript/clutz/googModule/goog_module.d.ts
src/test/java/com/google/javascript/clutz/goog_scope.d.ts
src/test/java/com/google/javascript/clutz/goog_scope.js
src/test/java/com/google/javascript/clutz/goog_scope_usage.ts

Instead of producing two incompatible types for the alias, now we emit a
"type alias, constructor var" pair.

fix(scope): support class/interface alias.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/goog_scope.js
src/test/java/com/google/javascript/clutz/goog_scope_templatized.d.ts
src/test/java/com/google/javascript/clutz/goog_scope_templatized.js

Type aliases need to explicitly list their type parameters:
```typescript
class B<T> {}
type A = B;  // wrong
type A<T> = B<T>  // correct
```

fix(interface alias): support templatized types.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/fn_inner_enum.d.ts
src/test/java/com/google/javascript/clutz/fn_inner_enum.js
src/test/java/com/google/javascript/clutz/privates.d.ts
src/test/java/com/google/javascript/clutz/static_provided.d.ts

Merge walkInnerSymbol and interface static logic. Emit auxilary
(non-provided) namespace only when non-empty.

fix: provided functions can be used as namespaces too.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/goog_module_class.d.ts
src/test/java/com/google/javascript/clutz/goog_module_class.js

Adds a test for goog.module + ES6 classes pattern.

fix(type alias): count the type alias as type used.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/undefined_provide.d.ts
src/test/java/com/google/javascript/clutz/undefined_provide.js
src/test/java/com/google/javascript/clutz/untyped_provide.d.ts

Typescript does not emit empty namespaces, thus correspondingly they
don't typecheck as valid symbols and are not useful to users.
Closes #239

do not emit empty namespaces.

---

src/test/java/com/google/javascript/clutz/invalid_names_usage.ts

The file was supposed to be part of
https://github.com/angular/clutz/commit/613701db83a14669bdda271b663a4cc559e8d8da
It is important to show how usage of invalid names works in presence of
noImplicitAny.

adds an usage of invalid names.

---

src/main/java/com/google/javascript/clutz/Constants.java
src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/nested_namespaces.d.ts
src/test/java/com/google/javascript/clutz/nested_namespaces.js
src/test/java/com/google/javascript/clutz/nested_namespaces_usage.ts

When a foo.bar is provided and we have emitted 'var bar' in namespace
foo, TS does not allow declaring namespace foo.bar. Since all var bar
has no internal references except in module exports, we use an internal
__clutz_alias to avoid the collision.
Note that the module shim still has the correct name, thus the alias in
invisible to any users through ES6 modules.
Closes #217

fixes issue with nested namespace.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/nested_namespaces.d.ts
src/test/java/com/google/javascript/clutz/nested_namespaces.js

Previously, "foo.bar" was considered shadowed by "foo.barBuz", which is
incorrect. It is only shadowed by "foo.bar.buz".

fix shadowing logic.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/extends_arraylike_with_platform.d.ts
src/test/java/com/google/javascript/clutz/extends_arraylike_with_platform.js

The parametrized type of IArrayLike is not handled (emit as any).
Fixes a bug where interfaces picked up static methods from backing
function assignment.

emit an index signature for classes implementing IArrayLike.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/resources/closure.lib.d.ts
src/test/java/com/google/javascript/clutz/general_with_platform.d.ts
src/test/java/com/google/javascript/clutz/types_externs_with_platform.d.ts

Clutz will emit GlobalEvent instead of Event, where GlobalEvent is an
type alias for Event.
This allows the following pattern to work:
namespace goog {
class Event extends Event {}
}

Add Event to the list of globalSymbolAliases.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/extending_function_field.d.ts
src/test/java/com/google/javascript/clutz/extending_function_field.js

It is possible that this is also a bug in closure, to consider the
inferred property as member of the derived class, and not part of the subclass.
In any case, clutz should generate a valid TS.

Fix field-method mismatch for inferred properties.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java

It would probably be ideal to additionally test this, but the method itself is private and the calling method does not seem to have any tests yet. Please advice. 
Also, it seems subideal to have to iterate linearly through `externSymbols`, but that was already the case and I did not want to make this change larger than necessary.

Avoid ConcurrentModificationException.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/type_renaming_with_emit_platform_externs.d.ts
src/test/java/com/google/javascript/clutz/type_renaming_with_emit_platform_externs.externs.js

Closure compiler adds wrong TemplateType (like IObject#KEY or
IObject#Value) for sereval types. The goal of this change is to detect
and skip these TemplateTypes.

Normalize template types names to support IObject# template keys.

---

src/main/java/com/google/javascript/gents/TypeAnnotationPass.java

Token.name() is deprecated and is going away soon. And, you don't need it anyway because the toStringTree output shows you the node type.

Remove call to Token.name()

---

build.gradle
src/main/java/com/google/javascript/gents/TypeScriptGenerator.java

When running for real, gents should use the local clang-format that the user is using.
Only during tests we should use the node_modules installed version.

feat: use system clang-format unless testing.

---

src/main/java/com/google/javascript/gents/ClassConversionPass.java
src/test/java/com/google/javascript/gents/singleTests/classes.ts
src/test/java/com/google/javascript/gents/singleTests/fields.ts
src/test/java/com/google/javascript/gents/singleTests/proto_methods.ts
src/test/java/com/google/javascript/gents/singleTests/static_methods.ts

Even fields which don't have type information should be emitted as class fields.
Partially addresses #345
Migrating from phabricator

emit all constructor fields as class fields

---

src/main/java/com/google/javascript/gents/GentsCodeGenerator.java
src/main/java/com/google/javascript/gents/TypeScriptGenerator.java
src/test/java/com/google/javascript/gents/TypeScriptGeneratorTests.java
src/test/java/com/google/javascript/gents/singleTests/externs_map.js
src/test/java/com/google/javascript/gents/singleTests/externs_map.ts
src/test/java/com/google/javascript/gents/test_externs_map.json

This supports the case where you want to be able to audit your uses of "any" after conversion, by aliasing them to something like `OldNoType`.
Also adds an extension point in TypescriptGeneratorTests to allow certain tests to be run with a different set of options from the other tests.
fixes #328

externsMap allows a type alias for 'any' to be supplied

---

src/main/java/com/google/javascript/gents/CommentLinkingPass.java
src/main/java/com/google/javascript/gents/Options.java
src/main/java/com/google/javascript/gents/StyleFixPass.java
src/main/java/com/google/javascript/gents/TypeAnnotationPass.java
src/main/java/com/google/javascript/gents/TypeConversionPass.java
src/main/java/com/google/javascript/gents/TypeScriptGenerator.java
src/test/java/com/google/javascript/gents/singleTests/interface.js
src/test/java/com/google/javascript/gents/singleTests/interface.ts

This change adds support for converting interface definitions
from ES5 style to proper TypeScript interfaces. It also adds
support for `@implements` on classes and interfaces.
This change was brought to you by LH927 from LCY --> FRA.

feat: interfaces

---

src/main/java/com/google/javascript/gents/ModuleConversionPass.java
src/test/java/com/google/javascript/gents/multiTests/module_imports/export_both.ts
src/test/java/com/google/javascript/gents/multiTests/module_imports/export_default.ts
src/test/java/com/google/javascript/gents/multiTests/provide_imports/export_module.ts
src/test/java/com/google/javascript/gents/multiTests/type_rewrite/imported_module.ts
src/test/java/com/google/javascript/gents/multiTests/type_rewrite/unimported_module.ts
src/test/java/com/google/javascript/gents/singleTests/classes.js
src/test/java/com/google/javascript/gents/singleTests/module_both.ts
src/test/java/com/google/javascript/gents/singleTests/module_class.js
src/test/java/com/google/javascript/gents/singleTests/module_class.ts
src/test/java/com/google/javascript/gents/singleTests/module_class2.js
src/test/java/com/google/javascript/gents/singleTests/module_class2.ts
src/test/java/com/google/javascript/gents/singleTests/module_default.ts

This change adds support for 'default exports' to gents.  See request
#329 .
Reference:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statem
ents/export

feat: Add support for `export default` in gents.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/index_signature_with_platform.d.ts
src/test/java/com/google/javascript/clutz/index_signature_with_platform.js

Closure supports referring to templatized type without passing
type parameters, i.e. a type C<T>, can be use bare as C. This change
adds support for using IArrayLike and IObject in such way.

fix: Support for IArrayLike and IObject used as bare types.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/MultiFileTest.java
src/test/java/com/google/javascript/clutz/depgraph/depgraph.d.ts
src/test/java/com/google/javascript/clutz/depgraph/root.js
src/test/java/com/google/javascript/clutz/depgraph/transitive_namespace.js

Previously, Clutz would ignore types that are contained in a namespace,
assuming they were just fields on that namespace. Now, Clutz will still
generate them if they are their own provide (from the list of transitive
provides).

fix: support transitive types shadowed by namespaces.

---

src/main/java/com/google/javascript/gents/TypeConversionPass.java
src/test/java/com/google/javascript/gents/singleTests/fields.js
src/test/java/com/google/javascript/gents/singleTests/fields.ts

This fixes a bug that would cause gents to generate duplicate fields and promote some assignments to field initializers inappropriately.
It changes behavior to only look in the constructor for fields. With some care to remove duplicates and leave the assignments in-place it would be possible to promote fields in other methods too.
fixes #358

Remove duplicate fields

---

src/main/java/com/google/javascript/gents/TypeConversionPass.java

I thought that closure-compiler 09/11 had already removed getType(), but alas it didn't and I missed some.

remove the last getType()s from gents

---

src/main/java/com/google/javascript/gents/ModuleConversionPass.java
src/test/java/com/google/javascript/gents/multiTests/module_imports/export_both.ts
src/test/java/com/google/javascript/gents/multiTests/module_imports/export_default.ts
src/test/java/com/google/javascript/gents/multiTests/provide_imports/export_module.ts
src/test/java/com/google/javascript/gents/multiTests/type_rewrite/imported_module.ts
src/test/java/com/google/javascript/gents/multiTests/type_rewrite/unimported_module.ts
src/test/java/com/google/javascript/gents/singleTests/module_both.ts
src/test/java/com/google/javascript/gents/singleTests/module_class.ts
src/test/java/com/google/javascript/gents/singleTests/module_class2.ts
src/test/java/com/google/javascript/gents/singleTests/module_default.ts

After discussions we have decided that we would like this to be a forcing function to encourage people to conform with the TypeScript style guide.

Remove support for `export default`.

---

src/main/java/com/google/javascript/gents/CommentLinkingPass.java
src/main/java/com/google/javascript/gents/RemoveGoogScopePass.java
src/main/java/com/google/javascript/gents/TypeScriptGenerator.java
src/test/java/com/google/javascript/gents/singleTests/goog_scope.js
src/test/java/com/google/javascript/gents/singleTests/goog_scope.ts

Summary:
Rewrite the AST, removing the `goog.scope` wrapper, so that the various module and class-based transformations can take place.
Partially Adresses #349

feat: Support goog.scope transformations in gents.

---

src/main/java/com/google/javascript/gents/PathUtil.java
src/main/java/com/google/javascript/gents/TypeScriptGenerator.java
src/test/java/com/google/javascript/gents/TypeScriptGeneratorMultiTests.java
src/test/java/com/google/javascript/gents/TypeScriptGeneratorTests.java
src/test/java/com/google/javascript/gents/multiTests/basenames_dont_collide/a/file.js
src/test/java/com/google/javascript/gents/multiTests/basenames_dont_collide/a/file.ts
src/test/java/com/google/javascript/gents/multiTests/basenames_dont_collide/b/file.js
src/test/java/com/google/javascript/gents/multiTests/basenames_dont_collide/b/file.ts

Use the whole file path as a hash key, so that files in different
directories that have the same basename do not overwrite one another.
fixes #348

Files with the same basename don't clobber each other.

---

src/test/java/com/google/javascript/gents/singleTests/inline_types.js
src/test/java/com/google/javascript/gents/singleTests/inline_types.ts

Note: Gents currently does not offer support for inline types for
functions so those tests are commented out.
Tests for #352.

test: Add tests for inline-types.

---

src/main/java/com/google/javascript/gents/CollectModuleMetadata.java
src/main/java/com/google/javascript/gents/ModuleConversionPass.java
src/test/java/com/google/javascript/gents/multiTests/import_rewrite/import.ts
src/test/java/com/google/javascript/gents/multiTests/module_imports/export_both.js
src/test/java/com/google/javascript/gents/multiTests/module_imports/export_both.ts
src/test/java/com/google/javascript/gents/multiTests/module_imports/export_named.js
src/test/java/com/google/javascript/gents/multiTests/module_imports/export_named.ts
src/test/java/com/google/javascript/gents/multiTests/module_imports/import_binding.js
src/test/java/com/google/javascript/gents/multiTests/module_imports/import_binding.ts
src/test/java/com/google/javascript/gents/multiTests/type_rewrite/import.ts

Fix for NPE when converting a goog.module with a destructured assignment.
Add support for importing a single destructured import value (#392).
Triggering code:
```javascript
goog.module('path.to.FooUser');
const {foo} = goog.require('path.to.foo');
```
Stack trace:
```
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.
null
Node(CONST): path/to/file_test.js:6:0
const {ImportedValue} = goog.require('path.to.file');
Parent(MODULE_BODY): path/to/file_test.js:1:0
goog.module('path.to.FileTest');
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:779)
at com.google.javascript.gents.ModuleConversionPass$ModuleExportConverter.collectMetdataForExports(ModuleConversionPass.java:178)
at com.google.javascript.gents.ModuleConversionPass$ModuleExportCo …
```

fix: Destructured values in modules cause NPE.

---

src/main/java/com/google/javascript/gents/CollectModuleMetadata.java
src/main/java/com/google/javascript/gents/RemoveGoogScopePass.java
src/main/java/com/google/javascript/gents/TypeScriptGenerator.java
src/test/java/com/google/javascript/gents/singleTests/goog_scope.js
src/test/java/com/google/javascript/gents/singleTests/goog_scope.ts

Replaces aliased names within goog.scope so that further class based transformations can take place.
Fixes #349

feat: Rewrite aliases in goog.scope.

---

src/main/java/com/google/javascript/gents/CommentLinkingPass.java
src/test/java/com/google/javascript/gents/singleTests/comments.js

Add $ to regex that matches on param names, so they get stripped.

---

src/main/java/com/google/javascript/gents/GentsCodeGenerator.java
src/main/java/com/google/javascript/gents/TypeConversionPass.java
src/test/java/com/google/javascript/gents/singleTests/parameter_prop.js
src/test/java/com/google/javascript/gents/singleTests/parameter_prop.ts

This updates constructor parameter properties to be marked `readonly` if the parameter is annotated with `@const` 
Partially addresses #382

Add readonly to const parameters properties in gents

---

src/main/java/com/google/javascript/gents/CollectModuleMetadata.java
src/main/java/com/google/javascript/gents/ModuleConversionPass.java
src/test/java/com/google/javascript/gents/multiTests/jslib_imports/import.ts
src/test/java/com/google/javascript/gents/multiTests/module_imports/export_sideeffect.ts
src/test/java/com/google/javascript/gents/multiTests/module_imports/import_binding.ts
src/test/java/com/google/javascript/gents/multiTests/type_rewrite/import.ts

Summary:
The current implementation adds empty export blocks to the file, if the file does not have an exports; however, empty export blocks are only needed to coerce a file to a module if has neither imports nor exports. 
To fix this, we augment the `FileModule` to record whether the module has any `goog.require`s, and then only add the empty block to the files without either.   When we do add the empty export block, also add a comment explaining its purpose.

fix: Only add empty export blocks when necessary

---

src/main/java/com/google/javascript/gents/TypeConversionPass.java

at com.google.javascript.rhino.Node.getString(Node.java:1116)
at com.google.javascript.gents.TypeConversionPass$FieldOnThisConverter.visit(TypeConversionPass.java:154)
Caused by: java.lang.UnsupportedOperationException: GETPROP 60 [length:
440] [source_file:path/to/file.js] is not a string node

fix: UnsupportedOperationException in TypeConversionPass

---

src/main/java/com/google/javascript/gents/CollectModuleMetadata.java
src/test/java/com/google/javascript/gents/multiTests/module_imports/import_assignment.js
src/test/java/com/google/javascript/gents/multiTests/module_imports/import_assignment.ts

Summary:
The current ‘no empty export’ detection mechanism doesn’t take into account cases where the goog.require is assigned to a value. (e.g. `const A = goog.require(‘A’);`)

fix: Don't add empty exports when assigning goog.require to a var.

---

src/main/java/com/google/javascript/gents/CommentLinkingPass.java
src/test/java/com/google/javascript/gents/singleTests/comments.js
src/test/java/com/google/javascript/gents/singleTests/comments.ts

Updates the comment regexes so that, instead of removing all blank lines
indiscriminately, we just remove matching lines if there is nothing in
the `keep` capture group.
fixes #385

Do not strip empty jsdoc lines used for spacing

---

src/main/java/com/google/javascript/gents/TypeConversionPass.java
src/test/java/com/google/javascript/gents/singleTests/functions.js
src/test/java/com/google/javascript/gents/singleTests/functions.ts
src/test/java/com/google/javascript/gents/singleTests/module_class3.js
src/test/java/com/google/javascript/gents/singleTests/module_class3.ts

Fixes:
```
DEFAULT_VALUE 12 [length: 13] [source_file: path/to/file.js] is not a string node
Node(EXPR_RESULT): path/to/file.js:20:4
this.children = children;
Parent(BLOCK): path/to/file_with_default_value.js:12:48
constructor(name, children = []) 
```

fix: Add support for constructor params with default values.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/nested_typedef_enum.d.ts
src/test/java/com/google/javascript/clutz/nested_typedef_enum.externs.js
src/test/java/com/google/javascript/clutz/nested_typedef_enum.js
src/test/java/com/google/javascript/clutz/nested_typedef_enum_usage.ts

This surprising pattern is from an actual piece of code encountered in the wild.
It is an obscure corner case, and it is unclear whether the NoType check is
correct or might trigger in other programs. I will try this change out on a
larger code base and see if it breaks things.

Support enums nested in typedefs that are defined in externs

---

src/main/java/com/google/javascript/gents/Options.java
src/main/java/com/google/javascript/gents/TypeScriptGenerator.java

- Don't store completed compiler passes in locals unless they are used
later.
- Add visibility & static modifiers where appropriate.
- Output single quotes instead of double quotes to reduce the work
needed by clang-format.

perf: Single quotes + free up completed compiler passes

---

src/main/java/com/google/javascript/gents/ModuleConversionPass.java
src/main/java/com/google/javascript/gents/NodeComments.java
src/main/java/com/google/javascript/gents/Options.java
src/main/java/com/google/javascript/gents/RemoveGoogScopePass.java
src/main/java/com/google/javascript/gents/TypeAnnotationPass.java
src/main/java/com/google/javascript/gents/TypeConversionPass.java
src/main/java/com/google/javascript/gents/TypeScriptGenerator.java
src/test/java/com/google/javascript/gents/TypeScriptGeneratorMultiTests.java
src/test/java/com/google/javascript/gents/TypeScriptGeneratorTests.java
src/test/java/com/google/javascript/gents/multiTests/type_rewrite/imported_module.ts
src/test/java/com/google/javascript/gents/multiTests/type_rewrite/unimported_module.ts
src/test/java/com/google/javascript/gents/singleTests/module_both.ts
src/test/java/com/google/javascript/gents/singleTests/module_class.ts
src/test/java/com/google/javascript/gents/singleTests/module_class2.ts
src/test/java/com/google/javascript/gents/singleTests/module_class3.ts

Gents already reports the failure location for the various code
visitors, but does not report a location when code generation fails. To
track down AST issues, also validate the AST before emit.

Validate the AST, print file name when codegen fails.

---

src/main/java/com/google/javascript/gents/CommentLinkingPass.java
src/test/java/com/google/javascript/gents/multiTests/import_rewrite/export.js
src/test/java/com/google/javascript/gents/multiTests/import_rewrite/export.ts

- Fix issue wherein all comments appear at the top of the file (before all code)
- Refactors CommentLinkingPass to improve readability.
More details:
When there is a newline between the @fileoverview and the goog.provide, then the comments strangely go out of sync.
== Works ====
```java
/** 
* @fileoverview the quick brown fox jumps over the lazy dog 
*/
goog.provide('foo.bar')
```
== Broken ====
```java
/** 
* @fileoverview the quick brown fox jumps over the lazy dog 
* notice that there is a blank line after this
*/
goog.provide('foo.bar')
```

fix: Fix issue wherein all comments appear at the top of the file

---

.travis.yml

Removing jdk7 doesn't seem to be taking effect in my Java8 PR, possibly
because I added it too late.  Attempting to update independently, so
that the Java 8 changes can be merged.

Update travis independently from java8 changes.

---

build.gradle
src/main/java/com/google/javascript/clutz/Constants.java
src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/main/java/com/google/javascript/gents/TypeAnnotationPass.java
src/test/java/com/google/javascript/gents/TypeScriptGeneratorMultiTests.java

Change clutz/gents to use Java8 and run Refaster over the codebase.
Note: closure-compiler is pinned at Guava v20, so not all Guava Java 8
goodness is available yet (v21) adds new convenience methods (namely,
FluentIterable -> Streams; ImmutableList.toImmutableList (collector))

Convert to Java 8

---

.travis.yml
DEVELOPER.md
README.md
npm-shrinkwrap.json
package.json
src/test/java/com/google/javascript/clutz/DeclarationSyntaxTest.java
src/test/java/com/google/javascript/gents/singleTests/classes.ts

Removes on demand installation of `typescript@next` as
that can create version mismatch between different developers.
Fixes some formatting that changed with clang-format 1.0.48.

Locking the node package dependencies.

---

src/main/java/com/google/javascript/gents/ModuleRenameLogger.java
src/main/java/com/google/javascript/gents/Options.java
src/main/java/com/google/javascript/gents/TypeScriptGenerator.java
src/test/java/com/google/javascript/gents/TypeScriptGeneratorMultiTests.java
src/test/java/com/google/javascript/gents/TypeScriptGeneratorTests.java
src/test/java/com/google/javascript/gents/multiTests/import_rewrite/log
src/test/java/com/google/javascript/gents/multiTests/module_imports/log

When configured with the option --log, gents will write the module
conversion into a log. This log will be used by tools downsteam to
modify files outside the scope of gents.
Each line of the log contains three comma separated strings - (OriginalName,
TSFile, DefaultExportName).
OriginalName is the original goog.module/goog.provide name.
TSFile - the name of the TypeScript file that contains the converted Closure module/namespace.
DefaultExportName - Gents never uses TS default exports. This means if the
original goog.module had a default export we generated a named export with a
specific name. This field contains that name. If there was no default export,
the field contains the empty string.

Adds a gents module rewrite log.

---

src/main/java/com/google/javascript/gents/ModuleRenameLogger.java
src/test/java/com/google/javascript/gents/TypeScriptGeneratorMultiTests.java

Because closure compiler visits files in non-deterministic order
(observed differently on Ubuntu vs. Travis) the test might fail on some
platforms. Instead of string comparison we parse the log in both
golden and emit and compare them as sets.
Closes #454

Make log comparison deteministic.

---

src/main/java/com/google/javascript/gents/ModuleConversionPass.java
src/test/java/com/google/javascript/gents/TypeScriptGeneratorMultiTests.java
src/test/java/com/google/javascript/gents/multiTests/converts_ts_module_require/already_converted_to_ts_keep.es5.js
src/test/java/com/google/javascript/gents/multiTests/converts_ts_module_require/already_converted_to_ts_keep.js
src/test/java/com/google/javascript/gents/multiTests/converts_ts_module_require/converts_ts_module_require.js

When gents encounters 'require('google3.foo.bar')' it can map it back
to a tscikle emitted blaze-bin/foo/bar.es5.js. An extra back mapping
is required to map to foo/bar.ts, which is what the final import should
emit.

Revert bazel's output file mapping when going over already converted TS.

---

src/main/java/com/google/javascript/gents/RemoveGoogScopePass.java
src/test/java/com/google/javascript/gents/singleTests/goog_scope_local_alias.js
src/test/java/com/google/javascript/gents/singleTests/goog_scope_local_alias.ts

@rkirov @dpurp Please review my attempt to fix https://github.com/angular/clutz/issues/453
Two fixes:
(1) The original assumption is that the node returned by `maybeRecordAndRemoveAlias()` is ought to be moved. This is not true. In some cases (for example `var foo = a.b.c;` where `a.b.c` comes from `goog.provide`), we detach this node and return the next node which has not been checked at all. We shouldn't simply move the next node in this case.
(2) Instead of checking if the alias matches goog.provide precisely, we could check if the alias matches goog.provide partially so that local partial alias works.

Fix local alias in goog.scope for goog.provide

---

src/main/java/com/google/javascript/gents/GentsCodeGenerator.java
src/main/java/com/google/javascript/gents/TypeAnnotationPass.java
src/main/java/com/google/javascript/gents/TypeConversionPass.java
src/test/java/com/google/javascript/gents/multiTests/goog_provide_rewrite/goog_scope.js
src/test/java/com/google/javascript/gents/multiTests/goog_provide_rewrite/goog_scope.ts
src/test/java/com/google/javascript/gents/singleTests/inner_types.js
src/test/java/com/google/javascript/gents/singleTests/inner_types.ts

@rkirov @dpurp PTAL
Fixes https://github.com/angular/clutz/issues/451
Gents doesn't know how to handle classes with inner typedefs.
PR 1/4: TypeScript doesn't have the closure equivalent of nested type alias inside classes. So we convert them into top level interfaces and rename its use in the file.

fix(gents): converts classes with inner typedefs to interfaces (1/4)

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/resources/closure.lib.d.ts
src/test/java/com/google/javascript/clutz/shadowed_global_with_platform.d.ts
src/test/java/com/google/javascript/clutz/shadowed_global_with_platform.js
src/test/java/com/google/javascript/clutz/shadowed_global_with_platform.usage.ts

Adds example of how this is needed for goog.events.EventTarget.
Fixes #472

Add EventTarget to the list of globals that need aliasing.

---

src/main/java/com/google/javascript/gents/TypeConversionPass.java
src/test/java/com/google/javascript/gents/singleTests/interface.js

https://github.com/google/closure-compiler/blob/ab4617a86346e659253593b11d2570fa26300415/src/com/google/javascript/jscomp/newtypes/JSTypeCreatorFromJSDoc.java#L85

fix(gents): An interface can only extend, but not implement interfaces.

---

src/main/java/com/google/javascript/gents/TypeAnnotationPass.java
src/test/java/com/google/javascript/gents/singleTests/inner_types.js
src/test/java/com/google/javascript/gents/singleTests/inner_types.ts

Function type interface members are still just interface members. They are no different from other members. This is already handled correctly by creating a `MEMBER_VARIABLE_DEF` .

Add a test case for function type interface member in typedefs.

---

src/main/java/com/google/javascript/gents/CollectModuleMetadata.java
src/main/java/com/google/javascript/gents/TypeAnnotationPass.java
src/main/java/com/google/javascript/gents/TypeConversionPass.java
src/main/java/com/google/javascript/gents/TypeScriptGenerator.java
src/test/java/com/google/javascript/gents/multiTests/goog_provide_rewrite/import.js
src/test/java/com/google/javascript/gents/multiTests/goog_provide_rewrite/import.ts

@dpurp @gmoothart @rkirov PTAL.
Closure annotated typedefs inside a class are converted into exported
top level interfaces in TypeScript. This PR supports renaming the use in
other files.
This only fixes goog.provide and is a no-op for goog.module

fix(gents): Reference renaming for classes with inner typedefs (2/4)

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/general_with_platform.d.ts
src/test/java/com/google/javascript/clutz/undefined_type.d.ts
src/test/java/com/google/javascript/clutz/undefined_type.js

In closure 'void' and 'undefined' are synonims, in TypeScript there
are important distinctions.
In TypeScript the 'void' and 'undefined' types are not mutually
assignable.
Also 'function f(callback:() => undefined); f(() => {})' is
invalid, the compiler forces you to explicitly add 'return undefined'.
However, with `f(callback: () => void)` the empty callback `() =>
{}` works.
With this change for both 'void'/'undefined' in closure, clutz emits
TS 'void' when alone in a function return position - '(...) => void'.
Otherwise, it will emit TS 'undefined'.
Fixes #296

Emit 'void' for all function return types.

---

src/main/java/com/google/javascript/gents/RemoveGoogScopePass.java
src/test/java/com/google/javascript/gents/singleTests/class_alias.js
src/test/java/com/google/javascript/gents/singleTests/class_alias.ts

Introduces a RewriteStatus inner class to track 'stillAttached'
state, separate from a null Node, which could mean nothing more to
process.

fixes rewriteGoogProvide when alias is last

---

src/main/java/com/google/javascript/gents/TypeConversionPass.java
src/test/java/com/google/javascript/gents/singleTests/destr.js
src/test/java/com/google/javascript/gents/singleTests/destr.ts

Constructors with destructuring cannot use the 'public' shorthand:
class C {
a: string;
constructor({a}: {a: string}) {
this.a = a;
}
}
Also fixes a bug where gents half-moved ctors with default args.  Since
CodeGenerator seems to avoid emitting 'public'/'private' keywords on
arguments with defaults. Back off and leave this transformation to
tslint.

Fixes NPEs for constructors with destructuring.

---

src/main/java/com/google/javascript/gents/CommentLinkingPass.java
src/main/java/com/google/javascript/gents/NodeComments.java
src/test/java/com/google/javascript/gents/singleTests/classes.ts
src/test/java/com/google/javascript/gents/singleTests/comments.js
src/test/java/com/google/javascript/gents/singleTests/comments.ts

Fixes https://github.com/angular/clutz/issues/493.
Current error pattern:
```javascript
a(
// comment
)
.b();
```
```javascript
if (a) {
// comment
}
else {
}
```

fix(gents) - Attempt to fix some comments conversion issues

---

src/main/java/com/google/javascript/gents/ModuleConversionPass.java
src/main/java/com/google/javascript/gents/Options.java
src/main/java/com/google/javascript/gents/PathUtil.java
src/main/java/com/google/javascript/gents/TypeAnnotationPass.java
src/main/java/com/google/javascript/gents/TypeScriptGenerator.java
src/test/java/com/google/javascript/gents/multiTests/converts_ts_module_require/a/b/c/deep_keep.es5.js
src/test/java/com/google/javascript/gents/multiTests/converts_ts_module_require/converts_ts_module_require.js
src/test/java/com/google/javascript/gents/multiTests/converts_ts_module_require/x/y/z/convert.js
src/test/java/com/google/javascript/gents/multiTests/converts_ts_module_require/x/y/z/convert.ts

Set the default root to be '.' (which is the one used by internal uses)
for parity between tests and users.

Emit a prefix for absolute module paths.

---

src/main/java/com/google/javascript/gents/TypeConversionPass.java
src/test/java/com/google/javascript/gents/singleTests/classes.js
src/test/java/com/google/javascript/gents/singleTests/classes.ts

Previously we get a nested class:
```javascript
class A {
constructor: any = class {  };
}
```

fix(gents): ignore @constructor annotations if inside goog.defineClass

---

src/main/java/com/google/javascript/gents/CommentLinkingPass.java
src/main/java/com/google/javascript/gents/ModuleConversionPass.java
src/main/java/com/google/javascript/gents/NodeComments.java
src/main/java/com/google/javascript/gents/TypeAnnotationPass.java
src/test/java/com/google/javascript/gents/singleTests/inline_types.js
src/test/java/com/google/javascript/gents/singleTests/inline_types.ts
src/test/java/com/google/javascript/gents/singleTests/interface.ts

Fixes #352.
Reference:
https://github.com/google/closure-compiler/wiki/Annotating-Types#function-declarations
One unrelated test (interface.ts) had to be fixed for this change to pass.
It put a wrong comment before this change, now it puts it (still wrongly)
elsewhere.

Added support for inline JsDoc types.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/infer_in_goog_module.d.ts
src/test/java/com/google/javascript/clutz/infer_in_goog_module.js

Clutz walks all `compiler.getTopScope().getAllSymbols()`. It appears
that for module objects
```javascript
goog.module('a.b');
const c = 0;
exports.c = c;
```
Closure does not register a corresponding 'a.b.c' symbol, while
```javascript
goog.module('a.b');
/** @const */
const c = 0;
exports.c = c;
```
does produce the symbol in question. To fix the first situation,
we also traverse the unemitted props on the 'a.b' object.
Fixes #506

Emit inferred props on a goog.module object.

---

src/main/java/com/google/javascript/clutz/Options.java
src/main/java/com/google/javascript/gents/Options.java
src/test/java/com/google/javascript/clutz/goog_scope_templatized.d.ts

For now replace with exact contents of setIdeMode:
https://github.com/google/closure-compiler/blob/7580f657e1d513efb06eb1ff9821e872a8b743c6/src/com/google/javascript/jscomp/CompilerOptions.java#L2044
except setAllowHotswapReplaceScript since both clutz and gents do not
support hotswapping code.
Surprisingly removing setAllowHotswapReplaceScript changes type
inference (what looks like for the better).

Inline deprecated options.setIdeMode call.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/infer_in_goog_module_with_platform.d.ts
src/test/java/com/google/javascript/clutz/infer_in_goog_module_with_platform.js

After #508 we started emitting all properties on export objects.
However, every object has inherited properties from the prototype
Object - __defineGetter__ etc.
TypeScript already models those internally, so there is no need to
emit them for every module object.

Only consider OwnProprertyNames when describing objects.

---

src/main/java/com/google/javascript/gents/CommentLinkingPass.java
src/test/java/com/google/javascript/gents/singleTests/comments.js
src/test/java/com/google/javascript/gents/singleTests/comments.ts

`.` matches any character except a newline therefore multi-lines annotations wouldn't be removed.

Remove @type annotation for multiple lines annotations.

---

.travis.yml
build.gradle
src/test/java/com/google/javascript/clutz/ClutzErrorManagerTest.java

For now nightly build failures are not blocking submission.
Also upgrade released version to 0527.

add closure nightly builds to Travis

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java

It appears we were too restrictive, for some of these words,
TypeScript is ok with 'namespace foo.<Word> {}'.
For example, 'namespace foo.interface {}' is ok.
Moreover, the fix for encountering reserved words is lossy, i.e.
misses more complex types, so we rather use it only when forced.

Reduce the list of reserved words.

---

README.md

The developers.google.com link redirects to the github link.
Alternatively, "https://developers.google.com/closure/compiler/" can be used.

Update Closure Compiler link in README

---

npm-shrinkwrap.json
package.json
src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/general_with_platform.d.ts
src/test/java/com/google/javascript/clutz/tte_promise_usage.ts

Remove 'Promise' from the list of platform APIs for which we generate
types. This means that clutz will reuse the Promise definition from
lib.d.ts, instead of attempting to translate closure's definition.
Closure already uses TTE's for the types of Promise and we have to
resort to hard-coding the translation.
Also, fix a test that failed in the presence of properly covariant
promises.

Upgrade clutz tests to TS2.4.

---

src/main/java/com/google/javascript/clutz/Options.java
src/test/java/com/google/javascript/clutz/DeclarationGeneratorTests.java
src/test/java/com/google/javascript/clutz/ProgramSubject.java
src/test/java/com/google/javascript/clutz/partial/missing_type.d.ts
src/test/java/com/google/javascript/clutz/partial/missing_type.js

When the flag is set, clutz will use setAssumeForwardDeclaration for all
unknown types, and not error on incomplete inputs.
Adds /partial/ directory for tests that run with that option on.

Add option for supporting partial program input to clutz.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/DeclarationSyntaxTest.java
src/test/java/com/google/javascript/clutz/general_with_platform.d.ts
src/test/java/com/google/javascript/clutz/implements_iterable_with_platform.d.ts
src/test/java/com/google/javascript/clutz/implements_iterable_with_platform.js
src/test/java/com/google/javascript/clutz/implements_iterable_with_platform_usage.ts
src/test/java/com/google/javascript/clutz/map_entries_with_platform.d.ts
src/test/java/com/google/javascript/clutz/map_entries_with_platform.js
src/test/java/com/google/javascript/clutz/map_entries_with_platform_user.ts

While Closure Compiler accepts code iterating types that implement
`[Symbol.iterator]`, it does not have a mechanism to represent computed
properties such as `Symbol.iterator`, so Clutz cannot really emit the
property itself.
As a workaround, simply emit a `[Symbol.iterator]` property for all
types that extend the well-known `Iterable` class, and special case its
return value for the well-known `IteratorIterable` class (called
`IteratorIterable` in Closure).
This also requires not emitting Iterable and IteratorIterable types, and
renaming the involved interfaces, such as `IteratorResult`.

Support custom [Symbol.iterator] implementations.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/aliased_enums.d.ts
src/test/java/com/google/javascript/clutz/enum.d.ts
src/test/java/com/google/javascript/clutz/enum.js
src/test/java/com/google/javascript/clutz/enum_unprovided.d.ts
src/test/java/com/google/javascript/clutz/enum_with_method.d.ts
src/test/java/com/google/javascript/clutz/enum_with_method.js
src/test/java/com/google/javascript/clutz/extern_enum.d.ts
src/test/java/com/google/javascript/clutz/fn_inner_enum.d.ts
src/test/java/com/google/javascript/clutz/inner_extern_enum.d.ts
src/test/java/com/google/javascript/clutz/interface.d.ts
src/test/java/com/google/javascript/clutz/nested_namespaces.d.ts
src/test/java/com/google/javascript/clutz/nested_typedef_enum.d.ts
src/test/java/com/google/javascript/clutz/provide_single_class.d.ts
src/test/java/com/google/javascript/clutz/static_enum.d.ts
src/test/java/com/google/javascript/clutz/static_inheritance_mismatch_nested_type.d.ts
src/test/java/com/google/javascript/clutz/static_provided.d.ts
src/test/java/com/google/javascript/clutz/typedef_inner_enum.d.ts

Emitting proper TypeScript enums allows the TypeScript compiler to make
additional inferences about the code, e.g. to support tagged unions,
type narrowing, exhaustive switches etc.
This also adds an `&{brand: never}` token to all other enums, to prevent
accidental assignment compatibility of values.
Because enums with the same members are not assignment compatible in TS
(enums are essentially nominally typed), this also has to update the
aliased enum emit.
Fixes #546.

Special case `@enum {number}` enums.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/DeclarationGeneratorTests.java
src/test/java/com/google/javascript/clutz/DeclarationSyntaxTest.java
src/test/java/com/google/javascript/clutz/partial/missing_type.d.ts
src/test/java/com/google/javascript/clutz/partial/missing_type.js

Adds supports for generic types. For now exclude 'partial' tests from
usage and syntax tests, so that we do not need to provide all
missing types.

Emit implicitly forward declared types for partialInputs.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/partial/missing_type.d.ts
src/test/java/com/google/javascript/clutz/partial/missing_type.js

For unknown to me reason those end up as NamedType instead of NoType,
thus they need special handling logic.

Emit missing types as template parameters.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/partial/missing_generic.d.ts
src/test/java/com/google/javascript/clutz/partial/missing_generic.js

Because closure allows generic types to be used without passing any
type arguments, incremental clutz cannot differentiate between
Foo a plain type or Foo a generic type that has implicilty '?' as
a type argument.
However, it is a syntactic mistake in TypeScript to use the generic type
without any type arguments if they do not have default values. To work
around this issue, in incremental mode, clutz will now emit '= any' for
all type parameters.

Emit a default type 'any' for all type parameters when partial input.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/all_optional_type.d.ts
src/test/java/com/google/javascript/clutz/all_optional_type.js
src/test/java/com/google/javascript/clutz/all_optional_type_usage.ts

Union types have two apis .getAlternates and
.getAlternatesWithoutStructuralTyping and it appears the second one
does not unify some types like 'Function'. Since, I see no downside to
using the second one, all calls are replaced for consistancy.
Describe the issue that is still present with general union types in
comments. Roughly, clutz sees types after closure has collapsed subtypes
into supertypes. Because of TypeScript features like weak types,
emitting post-collapse creates .d.ts that rejects valid code.

Make some type unions emit all constituent pieces.

---

src/main/java/com/google/javascript/gents/TypeScriptGenerator.java

I have google3-trunk clang-format installed locally which formats .ts differently causing test failures.

Make sure we're using the node_modules clang-format 

---

src/main/java/com/google/javascript/gents/ModuleConversionPass.java
src/main/java/com/google/javascript/gents/RemoveGoogScopePass.java
src/main/java/com/google/javascript/gents/StyleFixPass.java
src/main/java/com/google/javascript/gents/TypeAnnotationPass.java

In most cases I replaced the call with a call to reportChangeToEnclosingScope. In some cases I just deleted it entirely, which seems to have been fine, since I didn't see any test failures.

Remove calls to reportCodeChange, which is going away soon

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/module_typedef.d.ts
src/test/java/com/google/javascript/clutz/module_typedef.js
src/test/java/com/google/javascript/clutz/module_typedef_usage.ts

A type-only goog.module appears significantly different from one with
values, so we need a new code path for that.

Fix clutz to emit properly modules that default export a single typedef.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/main/java/com/google/javascript/clutz/Options.java
src/test/java/com/google/javascript/clutz/ProgramSubject.java
src/test/java/com/google/javascript/clutz/tsickle_emit.skip.tsickle.d.ts
src/test/java/com/google/javascript/clutz/tsickle_emit.skip.tsickle.js

This is going to be used for tsickle
(https://github.com/angular/tsickle) emitted files, where we plan to
glue up the .d.ts instead of reemitting in clutz.

Add an option to skip emit on certain suffixes.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/MultiFileTest.java
src/test/java/com/google/javascript/clutz/tsickle_emit/tsickle_emit.d.ts
src/test/java/com/google/javascript/clutz/tsickle_emit/tsickle_emit.skip.tsickle.js
src/test/java/com/google/javascript/clutz/tsickle_emit/uses_tsickle_type.js

Previously, we make sure all types used during the emit are themselves
emitted. This guarantees that the .d.ts is self contained.
To fully support skipEmitSuffix, the typeUsed processing should also
take care of not emitting types from files that end with the
skipEmitSuffix.

Add support for skipEmitSuffix in typesUsed processing.

---

src/main/java/com/google/javascript/gents/TypeConversionPass.java
src/test/java/com/google/javascript/gents/singleTests/enum.js
src/test/java/com/google/javascript/gents/singleTests/enum.ts

For string and number enums convert them to TypeScript, all other
types of enums are left as object literals.

Adds enum support in gents.

---

src/main/java/com/google/javascript/gents/ModuleConversionPass.java

The original `convertRequireToImportStatements()` function contains a big Cartesian product:
{`goog.require()`, `var x = goog.require()`, `var {x} = goog.require()`} × { `import x from 'goog:';`, `import {x} from './foo';`, `import * as x from './foo';`, `import './sideEffects';`} × {imported file kept in JS, imported file already in TS, imported file has side effect}
There are some hacks so all these conditions are handled in one function. For example `requiredNamespace` is appended with the local name in some cases and the suffix is stripped later.
This refactoring tries to split the destructuring case out. It also makes the variables really reflect what they contain. For example, `requiredNamespace` will be always the required namespace or module with no local names appended, making …

refactors import conversion pass

---

build.gradle
src/main/java/com/google/javascript/clutz/DeclarationGenerator.java

Files without goog.module or goog.provide, appear to report a new
synthetic provide 'module$src$...', which we now filter out in clutz.

Upgrade to closure v20171023

---

build.gradle

This PR updates the version of the Error Prone Gradle plugin used to `0.0.11` to expand the range of Gradle versions that can be used to build clutz. The current version, `0.0.9`, doesn't support Gradle versions above 3.4 as per [the table in the project's docs][1]:
> Gradle error-prone plugin version | Supported Gradle versions | Supported error-prone version | Supported javac version
> --------------------------------- | ------------------------- | ----------------------------- | -----------------------
> 0.0.1, 0.0.2                      | 1.8 - 1.11                | 1.+                           | 7
> 0.0.3                             | 1.8 - 1.12                | 1.+                           | 7
> 0.0.4                             | 2.1                       | 1.+ …

Update Error Prone Gradle plugin

---

src/main/java/com/google/javascript/clutz/Options.java
src/test/java/com/google/javascript/clutz/OptionsTest.java

This PR fixes the handling of quoted command line arguments by replacing the args4j string array option handler with one that does not split params on their whitespace.
As an example, running the following should respect the conventional shell quoting:
```bash
clutz a.js b.js c.js \
--externs foo.js bar.js 'baz qux.js' \
-o out.d.ts
```
And should read `baz qux.js` as a file name with a space in it.
The `StringArrayOptionHandler` included in args4j incorrectly split `baz qux.js` into two tokens.

Replace args4j StringArrayOptionHandler to handle quoted params

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java

This PR updates the comments emitted to strip [any line terminator code points][1] from the line.
[1]:http://www.ecma-international.org/ecma-262/6.0/#table-33

Remove line terminators from emitted comments

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java

- extract a constant for the matcher
- add a comment
- replace with underscore instead of stripping, so that it is easier to tell what was removed
Follow up to #588. Curiously, I've been unable to reproduce the behaviour reported by @whymarrh in a test case (Closure in my testing doesn't recognize those properties as typed symbols), but the fix is still generally correct in either way.

Refactor line terminator stripping.

---

README.md

Closes #589
Clarifies that:
- the build needs to be from source (kinda obvious maybe)
- this isn't a Java library but instead a command-line tool

Clarify build and usage in README

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/main/java/com/google/javascript/clutz/ImportRenameMapBuilder.java
src/main/java/com/google/javascript/clutz/InitialParseRetainingCompiler.java
src/test/java/com/google/javascript/clutz/partial/missing_base.d.ts
src/test/java/com/google/javascript/clutz/partial/missing_base.js

When parsing partial inputs, closure doesn't know the proper name of an imported symbol, so it emits it as part of the current module.
This PR walks the closure ast to grab the module id of the current file as well as the id of the import to construct a map of unresolved symbol names to resolved symbol names, and uses it to replace unresolved names when emitting NoResolvedType nodes.
Fixes #551

Resolve Module Bindings

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/partial/tte_promise_partial.d.ts
src/test/java/com/google/javascript/clutz/partial/tte_promise_partial.js

This class @extends Thenable, which means it should inherit a TTE type for
its .then() implementation.  But in partial mode, we don't see the base
class so we can't see that type.
We considered making it just infer to some broad any-based type, but in
in this particular case (the implementation of .then), if you lose the
TTE types then you have to manually annotate all the parameters to your
callback, so we deemed it ok to have a specific hack to see how common
this problem is.

hack around missing base class in partial mode for goog.deferred.Async

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/resources/closure.lib.d.ts
src/test/java/com/google/javascript/clutz/general_with_platform.d.ts
src/test/java/com/google/javascript/clutz/partial/date_like.d.ts
src/test/java/com/google/javascript/clutz/partial/date_like.js

Added a test to repro issue with DateLike declaration.  Fixed by introducing the indirection of GlobalDate by adding Date to the list of Global symbols, and adding GlobalDate to closure.lib.d.ts.
Fixes #602

Add Date to the set of Global symbols.

---

src/test/java/com/google/javascript/clutz/goog_module_export_redefined.d.ts
src/test/java/com/google/javascript/clutz/goog_module_export_redefined.js

Tsickle has to do an odd workaround to append moduleId to each
goog.module.
Turns out this changes the clutz emit significantly, and we need to have
a test to detect changes in that emit.

Adds a test that matches the emit pattern of tsickle.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/partial/date_like.d.ts
src/test/java/com/google/javascript/clutz/partial/missing_base.d.ts
src/test/java/com/google/javascript/clutz/partial/missing_generic.d.ts
src/test/java/com/google/javascript/clutz/partial/missing_platform_externs.d.ts
src/test/java/com/google/javascript/clutz/partial/missing_platform_externs.js
src/test/java/com/google/javascript/clutz/partial/missing_type.d.ts
src/test/java/com/google/javascript/clutz/partial/tte_promise_partial.d.ts

Since we declare everything in namespaces that start with ಠ_ಠ.clutz, any symbols that are under the ಠ_ಠ.clutz namespace will be resolved there, but if the missing symbols are in the platform externs (eg Node), then they won't be shadowed by the ಠ_ಠ.clutz namespace, as they were previously.

Don't emit ಠ_ಠ.clutz for missing symbols.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/partial/missing_base.d.ts
src/test/java/com/google/javascript/clutz/partial/missing_base.js
src/test/java/com/google/javascript/clutz/partial/tte_promise_partial.d.ts

Clutz attempts to leave out ctors that aren't necessary (e.g.
accepts same params as the parent class).  If Clutz can't see
the parent class, then it must emit a ctor because it can't
know whether the ctor is necessary or not.

emit subclass constructor when we can't see base constructor

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/partial/global_alias_missing.d.ts
src/test/java/com/google/javascript/clutz/partial/global_alias_missing.js

We already emit Global* for some global types that can get shadowed by
other namespace types. For example
goog.events.EventTarget;
/** @param {EventTarget} */
goog.events.listen
cannot be
namespace goog.events {
interface EventTarget {}
listen(t: EventTarget) {}
}
because the fn argument refers to the global one. Instead we have
GlobalEventTartget alias the global EventTarget and emit that name
instead.
With incremental clutz, we have to add that logic to the
emitNoResolvedType function too.

Attach the Global* emit logic for missing type too

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/inferred_provide.d.ts
src/test/java/com/google/javascript/clutz/inferred_provide.js
src/test/java/com/google/javascript/clutz/inferred_provide_usage.ts

Inferred symbols inside namespace provides are handled specially.
Previously, we had a fix for this issue, but only turned it on for
goog.modules. Now this is turned on for all inputs. Previous concerns
do not appear at least in the test suite.
This issue is more appearant with incremental clutz, because at least in
d3's case an ambient extern was masking the issue. That extern is no
longer visible in incremental scenario.
Note: this affects both modes (incremental and total) of clutz.

Fix for goog.provides with inferred symbols.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/partial/override.d.ts
src/test/java/com/google/javascript/clutz/partial/override.js

When a method @override's a superclass method, and we can't see the
superclass due to partial mode, we can't know whether the parameters
are optional or not.  Try to detect when this happens (when all the
parameters are type {?}) and defensively mark them all as optional.
This change is walking a fine line between multiple competing concerns.
For example, we don't want to rely on specifically @override because
of @inheritDoc, and we also want to do the right thing when the
superclass is visible.  See the test case for some examples.

mark partial overridden function parameters as optional

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/resources/partial_goog_base.js
src/test/java/com/google/javascript/clutz/ProgramSubject.java
src/test/java/com/google/javascript/clutz/partial/abstract_method_partial.d.ts
src/test/java/com/google/javascript/clutz/partial/abstract_method_partial.js

Knowing that 'goog.abstractMethod' is a function allows for incremental
clutz to emit 'C.prototype.fn = goog.abstractMethod' as a method and not
a field. TypeScript asserts that methods can only override other
methods, so this is crucial knowledge for incremental clutz.
To achieve this we add an extra mock version of base.js -
mock_goog_base.js that will be passed to every partial clutz
compilation. It will not affect the output in other ways than allowing
inference works to work better in its presence.

Add a partial_goog_base.js file that is used for all incremental clutz.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/main/java/com/google/javascript/clutz/ImportRenameMapBuilder.java
src/test/java/com/google/javascript/clutz/MultiFileTest.java
src/test/java/com/google/javascript/clutz/ProgramSubject.java
src/test/java/com/google/javascript/clutz/multifilePartial/default_object_exporter.d.ts
src/test/java/com/google/javascript/clutz/multifilePartial/default_object_exporter.js
src/test/java/com/google/javascript/clutz/multifilePartial/total.d.ts
src/test/java/com/google/javascript/clutz/partial/es6_missing_imported_base.d.ts
src/test/java/com/google/javascript/clutz/partial/es6_missing_imported_base.js

Using es6 syntax instead of /** @constructor */ annotations results in a different display name for a missing type in partial mode.  In an es6 the type is `foo` instead of the annoation method's `module$contents$foo`.  This PR modifies ImportRenameMapBuilder to produce mappings for both types of display name.
This PR also fixes an issue when importing an object, which contains the type to be used (ie imported foo, but used as `class quux extends foo.bar`.  In that case the displayname is of the form `foo.bar` or `module$contents$foo.bar`, but the importRenameMap only has a rename for the base of the display name.  To fix, the logic is modified to look for replacements of the portion of the display name up to the first period (if any).

Fix import renaming for es6 class syntax.

---

src/main/java/com/google/javascript/clutz/ImportRenameMapBuilder.java
src/test/java/com/google/javascript/clutz/partial/goog_module_get.d.ts
src/test/java/com/google/javascript/clutz/partial/goog_module_get.js

Similar to having to rename symbols that are imported in goog.modules(), closure doesn't get the right name for symbols imported inside a goog.scope block.  This PR modifies ImportRenameMapBuilder to collect the rename mappings inside goog.scope blocks, in addition to the existing goog.modules.

Rename missing imported symbols in goog.scope.

---

src/resources/partial_goog_base.js

Strict deps checks fails otherwise, requiring an actual dep on real
base.js which defeats the point.

Add a const goog block in partial_goog_base.

---

src/main/java/com/google/javascript/gents/ModuleConversionPass.java

The previous code immediately tried to use the retrieved module, which
is sometimes `null` (either because a dependency is missing from the
manifest, or perhaps also for newly-converted namespaces). There is
already an additional check in `validateImport` that provides much
better error output (which is now reachable).

Add a null check in ModuleImport.

---

src/main/java/com/google/javascript/gents/TypeConversionPass.java
src/test/java/com/google/javascript/gents/singleTests/enum.js
src/test/java/com/google/javascript/gents/singleTests/enum.ts

Previously we were assuming all numeric enums contained literal numbers.
Closes #628

Gents support for enums that have arithmetic expressions.

---

src/main/java/com/google/javascript/gents/TypeAnnotationPass.java
src/main/java/com/google/javascript/gents/TypeConversionPass.java
src/test/java/com/google/javascript/gents/singleTests/class_interface.js
src/test/java/com/google/javascript/gents/singleTests/class_interface.ts

Some closure users prefer to write /** @interface */ class IFoo, instead
of the more common function syntax. The intent is nevertheless for this
to be a pure interface and not class, so gents will correspondingly
convert that.
Some complications arrise from adding @extends and ES6's class extend
keyword and method/field definitions.
Closes #630,627

Gents translates ES6 classes with @interface annotation to interfaces.

---

src/main/java/com/google/javascript/gents/TypeScriptGenerator.java

Just skip emitting if the user does not provide that option.
Closes #633

Make gents not throw on missing rewritelog option.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/DeclarationGeneratorTests.java
src/test/java/com/google/javascript/clutz/ProgramSubject.java
src/test/java/com/google/javascript/clutz/base.js
src/test/java/com/google/javascript/clutz/outputBase/function_alias_output_base.d.ts
src/test/java/com/google/javascript/clutz/outputBase/function_alias_output_base.js
src/test/java/com/google/javascript/clutz/private_type.d.ts

Clutz had the assumption that every namespace it emits is a subnamespace of the ಠ_ಠ.clutz namespace.  This caused 2 problems:
1. Clutz refered to other types within the goog namespace with the ಠ_ಠ.clutz prefix.
2. Clutz refered to types in the ಠ_ಠ.clutz namespace within the goog namespace without the ಠ_ಠ.clutz prefix.
This PR fixes the above by only ever refering to a symbol inside a namespace with the ಠ_ಠ.clutz prefix when refering to a global symbol (ie in closure.lib.d.ts) while in the goog namespace.  In every other case, Clutz can rely on Typescript looking for the symbol in the parent namespaces if the prefix is omitted.

Fix emits in the goog namespace.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/resources/partial_goog_base.js
src/test/java/com/google/javascript/clutz/partial/missing_logger_dot_level.d.ts
src/test/java/com/google/javascript/clutz/partial/missing_logger_dot_level.js

Closure's log.js has this pattern:
/**
* @constructor
* @final
*/
goog.log.Level = goog.debug.Logger.Level;
Where the goog.debug.Logger.Level isn't part of the partial compilation.  Closure gives us a type based only on the type comment, totally ignoring the aliased symbol, so there's no easy way to solve the issue in clutz without a closure change.  This pattern only seems to show up in log.js, so just add the relevant symbols to partial_goog_base.js, which causes closure to give a type that knows about the alias.

Special case log.js's class aliases.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/partial/static_method.d.ts
src/test/java/com/google/javascript/clutz/partial/static_method.js

To ensure compatibility between goog.module and goog.provide code, symbols have to be renamed.  Previously, only top level references to goog.provide symbols were renamed.  This PR renames other references in a given file (ie method params).

Rename all references to symbols, not just top level ones.

---

src/main/java/com/google/javascript/gents/ModuleConversionPass.java
src/test/java/com/google/javascript/gents/multiTests/repeated_name_import/export.js
src/test/java/com/google/javascript/gents/multiTests/repeated_name_import/export.ts
src/test/java/com/google/javascript/gents/multiTests/repeated_name_import/import.js
src/test/java/com/google/javascript/gents/multiTests/repeated_name_import/import.ts

Ideally, we shouldn't be generating null nodes, but I could not
reproduce that case from the user reports.

Fix for importing symbol S from a module named something.S.

---

README.md
src/test/java/com/google/javascript/clutz/DeclarationGeneratorTests.java
src/test/java/com/google/javascript/clutz/MultiFileTest.java
src/test/java/com/google/javascript/clutz/ProgramSubject.java

Passing the environment variable UPDATE_GOLDENS=y when running declaration generators now auto updates all goldens.  _with_platform goldens and goldens with comments are exempted, so as not to mess things up.

Change DeclarationGeneratorTests and MultifileTests to auto update goldens.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/partial/renaming_with_generics.d.ts
src/test/java/com/google/javascript/clutz/partial/renaming_with_generics.js

The rewriter logic is now hooked in one more symbol emit code path.

Goog.require ambiguity rewriting now works for generic type params.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/resources/partial_goog_base.js
src/test/java/com/google/javascript/clutz/partial/goog_debug.d.ts
src/test/java/com/google/javascript/clutz/partial/goog_debug.js

This fixes the issue that Logger starts to appear in goog.debug
namespace. However, now we have to exclude partial_base from
debug/logger compilations, which also sucks :( WIP

Add goog.provide to the Logger symbols in partial_base.

---

src/main/java/com/google/javascript/clutz/ImportRenameMapBuilder.java
src/test/java/com/google/javascript/clutz/DeclarationGeneratorTests.java
src/test/java/com/google/javascript/clutz/MultiFileTest.java
src/test/java/com/google/javascript/clutz/partialCrossModuleTypeImports/goog_legacy_namespace_exporter.d.ts
src/test/java/com/google/javascript/clutz/partialCrossModuleTypeImports/goog_legacy_namespace_exporter.js
src/test/java/com/google/javascript/clutz/partialCrossModuleTypeImports/goog_module_importer.d.ts
src/test/java/com/google/javascript/clutz/partialCrossModuleTypeImports/goog_module_importer.js
src/test/java/com/google/javascript/clutz/partialCrossModuleTypeImports/total.d.ts

Previously all symbols in the knownGoogProvides list were aliased to the bare namespace, but if the import is destructured, need to alias to namespace + symbol name.

Make the knownGoogProvides whitelist work with destructuring imports.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/main/java/com/google/javascript/clutz/Options.java
src/test/java/com/google/javascript/clutz/OptionsTest.java
src/test/java/com/google/javascript/clutz/ProgramSubject.java
src/test/java/com/google/javascript/clutz/partial/bare_reexport.d.ts
src/test/java/com/google/javascript/clutz/partial/bare_reexport.js
src/test/java/com/google/javascript/clutz/test_known_class_aliases

The goog.module requires a type annotation to work, and the known class aliases map is read in from a file instead of being hard coded.

Refactor the known class aliases code to handle goog modules with class aliases.

---

src/test/java/com/google/javascript/clutz/ClutzErrorManagerTest.java
src/test/java/com/google/javascript/clutz/DeclarationSyntaxTest.java
src/test/java/com/google/javascript/clutz/DepgraphTest.java
src/test/java/com/google/javascript/clutz/MultiFileTest.java
src/test/java/com/google/javascript/clutz/OptionsTest.java

There's a check within google3 that wants this annotation.
It appears to be harmless(?) to add it.

mark tests as using the junit runner

---

src/main/java/com/google/javascript/clutz/Constants.java
src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/main/java/com/google/javascript/clutz/Options.java
src/test/java/com/google/javascript/clutz/ProgramSubject.java
src/test/java/com/google/javascript/clutz/partial/colliding_provide.d.ts
src/test/java/com/google/javascript/clutz/partial/colliding_provide.js

If a file A has
goog.provide('mything');
mything = 3;
and a file B has
goog.provide('mything.subnamespace');
mything.subnamespace = 4;
Then the code is nonsense but clutz has a workaround anyway.
In partial mode we look at A without knowledge of B, so we cannot apply
the workaround without providing a global set of broken inputs like
these.  This change adds support for the global set and hooks it up to
a command-line flag.

add a whitelist for aliasing goog.provides

---

src/main/java/com/google/javascript/clutz/AliasMapBuilder.java
src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/main/java/com/google/javascript/clutz/ImportBasedMapBuilder.java
src/main/java/com/google/javascript/clutz/ImportRenameMapBuilder.java
src/main/java/com/google/javascript/clutz/Options.java
src/test/java/com/google/javascript/clutz/OptionsTest.java
src/test/java/com/google/javascript/clutz/ProgramSubject.java
src/test/java/com/google/javascript/clutz/partial/bare_reexport.d.ts
src/test/java/com/google/javascript/clutz/partial/bare_reexport.js
src/test/java/com/google/javascript/clutz/test_known_class_aliases

Read goog.require statements to generate possible export aliases, instead of passing in a map as an option.
Refactor ImportRenameMapBuilder to extend an abstract class, so AliasMapBuilder can rely on the same infrastructure.  Only supports reexports in goog.module() files, continues to rely on KNOWN_CLASS_ALIASES for goog.provide() class aliases.

Better bare reexport

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/DeclarationGeneratorTests.java
src/test/java/com/google/javascript/clutz/partial/platform_goog_require.d.ts
src/test/java/com/google/javascript/clutz/partial/platform_goog_require.js

The import rewriter has to be run before the code that looks for global
aliases. For example:
const EventTarget = goog.require('goog.events.EventTarget');
/** @type {EventTarget} */
The name has to be expanded to goog.events.EventTarget, otherwise we
would rewrite it as GlobalEventTarget.

Fix interaction between importRewriter and Global aliases.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/DeclarationSyntaxTest.java
src/test/java/com/google/javascript/clutz/goog_promise_with_platform.d.ts
src/test/java/com/google/javascript/clutz/goog_promise_with_platform.js
src/test/java/com/google/javascript/clutz/partial/tte_promise_partial.d.ts
src/test/java/com/google/javascript/clutz/tte_promise.d.ts

Clutz hard codes translations for TTE types, and goog.Promise has 2 type parameters, which wasn't previously accounted for in the translations.
Had to turn on noStrictGenericChecks to make it compile, ts doesn't like extending promise-y things.

Improve the typings for goog.Promise.

---

build.gradle
src/main/java/com/google/javascript/gents/ModuleConversionPass.java
src/main/java/com/google/javascript/gents/TypeAnnotationPass.java
src/test/java/com/google/javascript/clutz/implements_iterable_with_platform.d.ts

Two changes required:
- The test output changed for a platform extern; this was an intentional
change in the upstream extern (the function param should have been {?}).
- In gents, set the "shorthand property" flag on all imports/exports.
This is related to the AST for statments like:
export {x as x};
This flag is saying whether the code is ok with that being emitted as
export {x};
which we want in all cases.  (If it's an {x as y}, where x!=y, then
the flag has no effect.)

update closure version to v20180204

---

src/main/java/com/google/javascript/clutz/AliasMapBuilder.java
src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/partial/bare_named_reexport.d.ts
src/test/java/com/google/javascript/clutz/partial/bare_named_reexport.js
src/test/java/com/google/javascript/clutz/partial/import_without_reexport.d.ts
src/test/java/com/google/javascript/clutz/partial/import_without_reexport.js

Previously, AliasMapBuilder optimistically produced the possible aliases for an import, without checking for a corresponding export.  This caused exports to be treated as aliases even if they weren't.  By only adding entries for variables that are known to be reexported, only actual aliases will be treated as such.

Only add entries to aliasMap if the imported variable is reexported.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/partial/aliased_template_argument.d.ts
src/test/java/com/google/javascript/clutz/partial/aliased_template_argument.js

Works around an issue where an aliased type used as a type parameter to an unknown type doesn't resolve to the original type.  Adding the type to typesUsed ensures that the type alias is emitted as a type.

Add forward declared noResolvedTypes to typesUsed.

---

src/main/java/com/google/javascript/clutz/Options.java

This enables outputting tracer data from the js compiler which will let us improve performance by tweaking compiler or jvm options.

Add an option to set compiler tracer mode from command line.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/partial/inner_typedef_npe.d.ts
src/test/java/com/google/javascript/clutz/partial/inner_typedef_npe.js

Usually closure inlines typedefs, but in partial mode with generics
involved it only resolves the name to $module$contents. Our secondary
types used pass has to deal with finding the typedef definition and
emitting it correctly.

Fixes emit in partial mode on module local typedefs used in generics.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/partial/optional_export_object_property.d.ts
src/test/java/com/google/javascript/clutz/partial/optional_export_object_property.js

We use visitProperty() for visiting object properties and for visiting certain namespace members.  If we're visiting a namespace member that is a type union including undefined, the old code would incorrectly use the question mark syntax for optionality.

Fix emit for optional properties on export objects.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/partial/iterator_record_extends.d.ts
src/test/java/com/google/javascript/clutz/partial/iterator_record_extends.js

It appears that records extending unknown records spuriously trigger
that branch. Since the use case of extending records is a lot more
common than Iterator classes/interfaces, I am turning off this branch
for incremental clutz.

Remove [Symbol.iterator()] from incremental clutz.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/class_alias.d.ts
src/test/java/com/google/javascript/clutz/goog_module_declare_legacy.d.ts
src/test/java/com/google/javascript/clutz/goog_module_export_redefined.d.ts
src/test/java/com/google/javascript/clutz/goog_scope.d.ts
src/test/java/com/google/javascript/clutz/multifilePartial/default_object_exporter.d.ts
src/test/java/com/google/javascript/clutz/multifilePartial/missing_imported_base.d.ts
src/test/java/com/google/javascript/clutz/partial/declare_legacy_namespace.d.ts
src/test/java/com/google/javascript/clutz/partial/declare_legacy_namespace_object_literal_export.d.ts
src/test/java/com/google/javascript/clutz/partial/es6_missing_imported_base.d.ts
src/test/java/com/google/javascript/clutz/partial/goog_module_get.d.ts
src/test/java/com/google/javascript/clutz/partial/missing_direct_ref_base.d.ts
src/test/java/com/google/javascript/clutz/partial/optional_export_object_property.d.ts
src/test/java/com/google/javascript/clutz/partial/override.d.ts
src/test/java/com/google/javascript/clutz/partial/platform_goog_require.d.ts
src/test/java/com/google/javascript/clutz/partial/separated_destructure.d.ts
src/test/java/com/google/javascript/clutz/partial/tte_promise_partial.d.ts
src/test/java/com/google/javascript/clutz/partialCrossModuleTypeImports/goog_legacy_namespace_exporter.d.ts
src/test/java/com/google/javascript/clutz/partialCrossModuleTypeImports/goog_module_importer.d.ts

Also reworks support for declareLegacyNamespace() to ensure that there's an alias for the instance half.

Fixes the regression on the static-instance split for classes.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/main/java/com/google/javascript/clutz/PlatformSymbols.java
src/test/java/com/google/javascript/clutz/generator_with_platform.d.ts
src/test/java/com/google/javascript/clutz/generator_with_platform.js
src/test/java/com/google/javascript/clutz/partial/generator_partial.d.ts
src/test/java/com/google/javascript/clutz/partial/generator_partial.js

In closure generator functions implicitly are defined as functions that
return a Generator<T> type. In TypeScript, the closest thing to
Generator type is the IterableIterator.
The difference boils down to the the two methods return and throw, that
are part of the Generator interface in closure, but in TS they are
optional methods on the Iterator<T> type.
This change makes it so that we emit Genarator as IterableIterator in
the .d.ts. Tests added for both partial and total mode.
Special care for not emitting builtins Iterator and Generator, which
appear even if the externs they are defined in are not passed to the
compilation.

Allow clutz to handle ES6 generator functions.

---

src/main/java/com/google/javascript/clutz/PlatformSymbols.java
src/resources/closure.lib.d.ts

This library defines goog.vec.Float32Array
https://github.com/google/closure-library/blob/17b6f4d1142d931dcdc5845475af288d5d13d447/closure/goog/vec/float32array.js#L28
while this one in the same namespace wants to refer to the global one
https://github.com/google/closure-library/blob/17b6f4d1142d931dcdc5845475af288d5d13d447/closure/goog/vec/vec.js#L43
so it causes shadowing in Clutz.

add Float32Array and 64 to list of global workarounds

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java

A recent change in closure made window externs appear duplicated as
this.foo too.
https://github.com/google/closure-compiler/commit/f3bc96d9ebc296ee79fa1f4c8051f8db5d51f709
Original author @kevinoconnor7

Upstreaming fix to skip this.props coming the window object.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/nested_namespace_unprovided.d.ts
src/test/java/com/google/javascript/clutz/nested_namespace_unprovided.js
src/test/java/com/google/javascript/clutz/types.d.ts
src/test/java/com/google/javascript/clutz/undefined_provide.d.ts

Previously, we just emitted GlobalObject (alias for Object). However, we
do have enough information to emit an objectl literal type, even though
closure does not report those types as proper record types.
Especially for inferred namespaces this option is preferable to the
opaque object type.
For a real opaque 'Object' types instead of 'GlobalObject', clutz now
emits '{}' which is equivalent in TypeScript.

Emit object literal types when visiting objects.

---

src/main/java/com/google/javascript/gents/ModuleConversionPass.java
src/test/java/com/google/javascript/gents/multiTests/exported_default_obj/exporter.js
src/test/java/com/google/javascript/gents/multiTests/exported_default_obj/exporter.ts
src/test/java/com/google/javascript/gents/multiTests/exported_default_obj/importer.js
src/test/java/com/google/javascript/gents/multiTests/exported_default_obj/importer.ts
src/test/java/com/google/javascript/gents/singleTests/module_default_export_obj.js
src/test/java/com/google/javascript/gents/singleTests/module_default_export_obj.ts

Gents tries to not use default exports to account for an internal style
rule to not use default exports. However, some default exports are
trivial obj literals that just safe typing for the author.
class C {}
class D {}
exports = {C, D};
After this change gents will translate this file as if it was writen in
the equivalent style of:
exports.C = C;
exports.D = D;
Closes #527

Do not consider simpler default obj lit exports as default exports.

---

src/main/java/com/google/javascript/gents/TypeConversionPass.java
src/test/java/com/google/javascript/gents/singleTests/inner_typedef_alias.js
src/test/java/com/google/javascript/gents/singleTests/inner_typedef_alias.ts

Paterns of the shape:
class C {}
/** @typedef {...} */
C.Alias = Other;
where throwing off gents, because we were trying emit twice: once for
Alias and once for Other. Fix by not considering Other in such cases.

Fix gents not to throw when visiting a typedef alias.

---

npm-shrinkwrap.json
src/main/java/com/google/javascript/gents/Options.java

This allows the node wrapper to pass manifest files instead of all files to gents, which causes E2BIG failures.

Accept --dependenciesManifest and --sourcesManifest

---

src/test/java/com/google/javascript/clutz/fn_params.d.ts
src/test/java/com/google/javascript/clutz/inferred_obj.d.ts
src/test/java/com/google/javascript/clutz/inferred_obj.js
src/test/java/com/google/javascript/clutz/invalid_names.d.ts

It appears a number of invalid property names are simply no longer
reported seen by clutz, because the undelying closure object has
pre-filtered them.
This means we no longer print '//!! clutz skipped property foo' type of
comments on them.

Fix test broken with latest closure head.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/goog_promise_with_platform.d.ts
src/test/java/com/google/javascript/clutz/interface.d.ts
src/test/java/com/google/javascript/clutz/interface.js
src/test/java/com/google/javascript/clutz/interface_provided_static_method.d.ts
src/test/java/com/google/javascript/clutz/interface_provided_static_method.js
src/test/java/com/google/javascript/clutz/interface_static_method.d.ts
src/test/java/com/google/javascript/clutz/interface_static_method.js
src/test/java/com/google/javascript/clutz/interface_usage.ts

In Closure, JS code can legally define static properties on interfaces:
/** @interface */
class Foo {
static bar() { return 'a'; }
}
This is also allowed on interfaces not using the newer class syntax, but
just prototype declarations.
In TypeScript, this can be represented as a namespace object that
matches the interface's name:
// A normal interface definition.
interface A {
foo(): void;
}
namespace A {
// Declare a static function in A
export function bar() {
return 'bar';
}
}
// Can invoke bar on A.
A.bar();
// B can still impement A with only the `foo` method defined.
class B implements A {
foo() {}
}

Emit static properties of interfaces.

---

src/main/java/com/google/javascript/gents/ModuleConversionPass.java
src/test/java/com/google/javascript/gents/singleTests/module_both.js
src/test/java/com/google/javascript/gents/singleTests/module_both.ts
src/test/java/com/google/javascript/gents/singleTests/typedef_obj_export.js
src/test/java/com/google/javascript/gents/singleTests/typedef_obj_export.ts

Previously this caused an NPE due to missing nodes. It appears we held
back unrolling
```
let x = 0;
export {x};
```
into
```
export let x = 0;
```
because of possibility of mutable bindings. I think the vast majority of
bindings are immutable (for example typedefs), so this cl reverts this
decision. It prefers the simpler syntactic output for the majority,
while accepting that in some cases the translation is not semantically
accurate.

Fixes exporting typedefs through obj lit.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/DeclarationGeneratorTests.java
src/test/java/com/google/javascript/clutz/DeclarationSyntaxTest.java
src/test/java/com/google/javascript/clutz/MultiFileTest.java
src/test/java/com/google/javascript/clutz/aliasedInterface/alias_for_interface.js
src/test/java/com/google/javascript/clutz/aliasedInterface/aliasedInterface.d.ts
src/test/java/com/google/javascript/clutz/aliasedInterface/aliased_interface_with_static.js
src/test/java/com/google/javascript/clutz/aliasedInterface/user.ts
src/test/java/com/google/javascript/clutz/partial/partial_alias_for_interface.d.ts
src/test/java/com/google/javascript/clutz/partial/partial_alias_for_interface.js
src/test/java/com/google/javascript/clutz/partial/partial_aliased_interface.d.ts
src/test/java/com/google/javascript/clutz/partial/partial_aliased_interface.js

While #763 more systematically emitted static properties of interfaces,
users in some situations could still not access them. More specifically,
if an interface with static properites was re-exported (aliased), Clutz
would only emit a `type Alias = Actual` re-export, but not a
corresponding variable `var Alias: typeof Actual`.
This change fixes the problem by emitting `var` aliases for interfaces
with static properties.

Emit value aliases for interfaces with static props.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/static_this_templated_prop.d.ts
src/test/java/com/google/javascript/clutz/static_this_templated_prop.js

Previously, this would crash because of the popular "let me use an empty
list here" issue.

Handle static props using an @template this.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/tte_promise.d.ts
src/test/java/com/google/javascript/clutz/tte_promise.js
src/test/java/com/google/javascript/clutz/tte_promise_usage.ts

Keeps Clutz emitted AngularJS promise type close to the TS AngularJS type declaration.
When the callback function of `.then()` returns a `promise<never> | T` the TS AngularJS type declaration is smart enough to prune `promise<never>` and return just `promise<T>` (see [AngularJS .d.ts on DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/374598de675780b1312912d43dff88f9fbfcf0d8/types/angular/index.d.ts#L1201)). This PR attempts to port that functionality to Clutz.
The TypeScript [built-in promise](https://github.com/Microsoft/TypeScript/blob/v2.9.2/lib/lib.es5.d.ts#L1336) doesn't have this so don't prune `never` for any `.then` functions.

Special case AngularJS promise.then

---

src/main/java/com/google/javascript/clutz/AliasMapBuilder.java
src/main/java/com/google/javascript/clutz/ImportBasedMapBuilder.java
src/test/java/com/google/javascript/clutz/partial/module_reexport_with_module_obj.d.ts
src/test/java/com/google/javascript/clutz/partial/module_reexport_with_module_obj.js

Now clutz understands the pattern:
```
goog.module('bare.named.reexport');
const Mod = goog.require('original.module');
exports.x = Mod.x;
```
and generates proper reexports. By necessity of incremental mode it
generates a type and var reexport of x, even if it is only a value or
only a type.

Support aliases through module objects.

---

src/main/java/com/google/javascript/clutz/PlatformSymbols.java

Closure Compiler added `WorkerOptions` to the externs in https://github.com/google/closure-compiler/commit/31886b0d5e6bad55d1b2a561f5b7c5bae8bc485e.
fixes #781

Fix for latest Closure Compiler externs

---

src/test/java/com/google/javascript/clutz/base.js
src/test/java/com/google/javascript/clutz/fn_params_with_platform.d.ts
src/test/java/com/google/javascript/clutz/general_with_platform.d.ts
src/test/java/com/google/javascript/clutz/partial/es6_missing_imported_base.d.ts
src/test/java/com/google/javascript/clutz/partial/platform_goog_require.d.ts

This change restores a green build by fixing one bug and checking in new
baselines for the failing tests.
I added a file comment to base.js to show what it's for, and added a
newly required annotation on it.

update tests to new closure upstream

---

README.md

This uses the google-internal markdown formatter as a one-time
reformat of the README file.  Because it is google-internal I
cannot hook it into the build, but I figure at least a one-time
formatting pass here will make the file a little less gross for
subsequent edits.
(I also investigated using prettier.io's formatter but it wants to
rewrite the JS snippets within the README too.)

reformat the README

---

build.gradle

Last update was in Feb 2018.  This puts us on Oct 2018.
Realistically clutz is developed against tip of tree closure, but this
puts the 'release' build tests closer to reality.

update closure compiler version

---

src/main/java/com/google/javascript/clutz/PlatformSymbols.java
src/resources/closure.lib.d.ts

It needs the same scoping workaround as we do for other globals like
Object.

handle the global 'Storage' type

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/circular_prototype.d.ts
src/test/java/com/google/javascript/clutz/circular_prototype.js

The cannonical example being:
```
/** @const */
let a = {};
a.b = a;
```
For now, just detect simple loops (property points to the parent), and
avoid emitting the property. Instead mark the failed to emit property
with a comment.

Fix for clutz not failing on circular inferred objects.

---

src/test/java/com/google/javascript/clutz/async_await_with_platform.d.ts

from `com.google.javascript:closure-compiler:1.0-20181121.190252-418`

Fix test of async_await_with_platform for latest Closure Compiler

---

src/main/java/com/google/javascript/clutz/Options.java

This enables parsing code like async generators and for await.
All internal tests pass. See downstreaming change at cl/223155956

Consume ES_NEXT from clutz

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/ctor_func.d.ts
src/test/java/com/google/javascript/clutz/ctor_func.js
src/test/java/com/google/javascript/clutz/goog_promise_with_platform.d.ts
src/test/java/com/google/javascript/clutz/static_this_templated_prop.d.ts
src/test/java/com/google/javascript/clutz/this_type.d.ts
src/test/java/com/google/javascript/clutz/this_type.js
src/test/java/com/google/javascript/clutz/this_type_param.d.ts
src/test/java/com/google/javascript/clutz/this_type_param.js
src/test/java/com/google/javascript/clutz/this_type_param_generics.d.ts
src/test/java/com/google/javascript/clutz/this_type_param_generics.js
src/test/java/com/google/javascript/clutz/this_type_param_generics_usage.ts

fixes #709 
Additionally, these forms are supported:
```js
/**
* @return {!GenericClass<T>}
* @this {T}
* @template T
*/
A.prototype.foo = function() {
return new GenericClass(this);
};
/**
* @return {!Array<T>}
* @this {T}
* @template T
*/
A.prototype.array = function() {
return [this];
};
/**
* @return {!Object<string, T>}
* @this {T}
* @template T
*/
A.prototype.object = function() {
return {foo: this};
};
/**
* @return {{foo: T}}
* @this {T}
* @template T
*/
A.prototype.record = function() {
return {foo: this};
};
/**
* @param {string} str
* @this {Function}
*/
A.func = function(str) {
};
```
are converted to
```ts
class A {
array < T > (this : T ) : T [] ;
foo < T > (this : T ) : GenericClass < T > ;
object < T > (this : T ) : { [ key: string ]: T } ;
record < T > (this : T ) : { foo …
```

Improve this type

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/main/java/com/google/javascript/clutz/Options.java
src/test/java/com/google/javascript/clutz/OptionsTest.java

This is quite useful because the default externs are essential.
The default behavior (no externs) is not changed.

Add env option to load default externs

---

src/main/java/com/google/javascript/clutz/Options.java
src/main/java/com/google/javascript/gents/Options.java

Also, hides warnings from PhaseOptimizer. Both of these changes, do not
seem to affect clutz/gents capabilities, but rather just annoy users.

Turn off conformance checks for clutz and gents.

---

src/main/java/com/google/javascript/clutz/Options.java
src/main/java/com/google/javascript/gents/Options.java
src/test/java/com/google/javascript/clutz/OptionsTest.java
src/test/java/com/google/javascript/gents/OptionsTest.java

It's useful using with `find` and `xargs`.
```console
$ find ./foo -type f -name '*.js' | xargs clutz --externs extern1.js extern2.js --
```
http://args4j.kohsuke.org/args4j/apidocs/org/kohsuke/args4j/spi/StopOptionHandler.html

Add option terminator "--" to CLI

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/main/java/com/google/javascript/clutz/PlatformSymbols.java
src/test/java/com/google/javascript/clutz/types_externs_with_platform.d.ts
src/test/java/com/google/javascript/clutz/types_externs_with_platform.js

`NamedNodeMap` is templatized in Closure (historical issue of DOM) but not in TypeScript like `NodeList` or `MessageEvent`. 
- https://github.com/google/closure-compiler/blob/50713dceb16b369f8f317e5b49e8a9dec2b47496/externs/browser/w3c_dom1.js#L463-L471
- https://github.com/Microsoft/TypeScript/blob/ee25cdecbca49b2b5a290ecd65224f425b1d6a9c/lib/lib.dom.iterable.d.ts#L127

Fix NamedNodeMap

---

src/main/java/com/google/javascript/clutz/PlatformSymbols.java

Currently [clutz CI is failed](https://travis-ci.org/angular/clutz/jobs/465108148) because latest compiler https://github.com/google/closure-compiler/commit/91c0ace5eeeae92912e12bd84617eaf60ea7f536 introduced `AsyncIteratorIterable`.
clutz should map it to [AsyncIterableIterator](https://github.com/Microsoft/TypeScript/blob/71286e3d49c10e0e99faac360a6bbd40f12db7b6/src/lib/esnext.asynciterable.d.ts) like `IteratorIterable`.

Map AsyncIteratorIterable to AsyncIterableIterator for latest Closure Compiler

---

src/main/java/com/google/javascript/clutz/PlatformSymbols.java

Currently [clutz CI is failed](https://travis-ci.org/angular/clutz/jobs/466982084) because latest compiler introduced `OffscreenCanvas` in https://github.com/google/closure-compiler/commit/2738c0907a0a5791ebf28ec32a5f40988a5ace8d.

Add OffscreenCanvas to CLOSURE_EXTERNS_NOT_USED_IN_TYPESCRIPT

---

src/main/java/com/google/javascript/clutz/PlatformSymbols.java

For https://github.com/google/closure-compiler/commit/aed8df734fac7fed10e5f7c9f6582a659b7b1a63
But this test is too flaky...

Add FullscreenOptions to CLOSURE_EXTERNS_NOT_USED_IN_TYPESCRIPT list

---

README.md

`gradlew` makes sure to use the wrapped gradle, pinning it to the right version.

Use the gradlew command to build

---

src/test/java/com/google/javascript/clutz/DeclarationGeneratorTests.java
src/test/java/com/google/javascript/clutz/ProgramSubject.java

We need this so that we can override it in the internal environment and
run tests from a different file layout.
No functional change for github tests.

Add SOURCE_ROOT variable to make root for file access configurable.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/main/java/com/google/javascript/clutz/PlatformSymbols.java
src/test/java/com/google/javascript/clutz/MultiFileTest.java

- new variable ADDITIONAL_CLOSURE_EXTERNS_NOT_USED_IN_TYPESCRIPT for
extensions of externs.
- using SOURCE_ROOT for MultiFileTest
- empty files filtering adjustment.

More fixes to enable running Clutz tests in other environments.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/inner_provide_with_inner_symbol.d.ts
src/test/java/com/google/javascript/clutz/inner_provide_with_inner_symbol.js

Fixes a bug introduced by https://github.com/angular/clutz/commit/65e524ba2c1c341966eb3415682aa1ba21bc8c27
where we would emit inner classes twice under some circumstances.

Emit each inner class once.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/class_extends_array.d.ts
src/test/java/com/google/javascript/clutz/general_with_platform.d.ts

The [symbol.iterator] emit is quite hacky because it just tests whether
Iterable is implemented anywhere through the extends/implements chain.
However, in scenarios where the implements clause is reachable through
an extended base class, the actual emit is not needed.
A recent change in closure, made it so that the always-present (even
without externs) Array types implement Iterable. This requires that the
symbol iterator code skips reemiting [symbol.iterable] for superclasses
of Array. Actually emitting [symbol.iterable] exposes another issue
where the platform .d.ts for Array expects [symbol.iterable] to be
IteratorIterable, but we can only reasonably emit Iterable given the
partial compilation of incremental clutz.
This change simply detects this scenario and avoid emitting.
Also, pick …

Adjust [symbol.iterator] emit to ignore classes extending Array.

---

.circleci/config.yml
.travis.yml
README.md

Blocked on https://github.com/angular/clutz/pull/838 which fixes the CI failures on `master`

build: switch to circleci

---

src/main/java/com/google/javascript/gents/Options.java
src/test/java/com/google/javascript/gents/singleTests/functions.js
src/test/java/com/google/javascript/gents/singleTests/functions.ts

Changes the gents output language to ECMASCRIPT2015_TYPED.
Not sure why the output language matters for gents, but it has been the
recommeneded fix from Closure team.
Fix #853

Proper fix for #853.

---

src/main/java/com/google/javascript/gents/ModuleConversionPass.java
src/test/java/com/google/javascript/gents/singleTests/enum.js
src/test/java/com/google/javascript/gents/singleTests/enum.ts

input:
```javascript
goog.module('enum');
/** @enum {number} */
const E = {A : 1000};
exports.E = E;
```
actual:
```typescript
export enum E {A = 1E3};
```
expect:
```typescript
export enum E {A = 1000};
```
What happened?
* When converting JavaScript assignment statements (`exports.E = E`) to TypeScript `export` keyword we create a new export node and drops it inline as the parent of the actual declaration node (`exportNode declarationNode;`). We then set the source info from the assignment statement on the new export node. That is correct because that's where the export is coming from. But we shouldn't do that recursively. Overwriting the source info of the declaration node and its sub tree with the source info of the assignment doesn't make sense. The declaration node is completely …

Fix a bug that gents converts number values in exported numeric enums to scientific notation.

---

README.md
src/main/java/com/google/javascript/gents/CommentLinkingPass.java
src/test/java/com/google/javascript/gents/multiTests/goog_provide_rewrite/goog_scope.ts
src/test/java/com/google/javascript/gents/singleTests/class_interface.ts
src/test/java/com/google/javascript/gents/singleTests/comments.js
src/test/java/com/google/javascript/gents/singleTests/comments.ts
src/test/java/com/google/javascript/gents/singleTests/enum.js
src/test/java/com/google/javascript/gents/singleTests/enum.ts

Removes @enum {string} and @enum {number} JsDoc. ￼…
@enum {string|number} without any additional doc doesn't add much value
in TypeScript.
If additional documentation is present, then keep @enum <explanation>
without the type.
For enums that are not strings or numbers, keep the type in JsDoc.

 Removes @enum {string} and @enum {number} JsDoc.

---

src/test/java/com/google/javascript/clutz/partial/enum_alias.d.ts
src/test/java/com/google/javascript/clutz/partial/enum_alias.js

The current emit is wrong - self circular. Closure team wants to land a
change that changes it into another (also wrong emit), turn off test to
unblock that.
https://github.com/angular/clutz/issues/862 to track proper fix.

Turn off enum_alias test by removing enum annotation.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/inner_class_named_export.d.ts
src/test/java/com/google/javascript/clutz/inner_class_named_export.js
src/test/java/com/google/javascript/clutz/inner_class_named_export_usage.ts

Somehow despite all existing machinery we missed this case. Fix simply
extends the existing walkInnerSymbols for non-default exports.
Fixes #865

Fix clutz emit for inner classes inside named exports.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/goog_promise_with_platform.d.ts
src/test/java/com/google/javascript/clutz/tte_promise.d.ts

This is more consistent with the original JS APIs, which do not require the same class to be passed in.

Accept PromiseLike<T> in resolve() methods

---

src/test/java/com/google/javascript/clutz/infer_in_goog_module.d.ts

Closure's inference algorithm has changed - the directly infereable
expressions  `const a = '0'` are treated differently from inferable
expressions that go through some indirection - `const b = f();`.

Upgrade golden after a Closure compiler change.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/inner_unprovided_type.d.ts
src/test/java/com/google/javascript/clutz/inner_unprovided_type.js

Clutz mainly emits goog.provide symbols (goog.module exports appear as
such to clutz). However, sometimes that is not enough, there are two
extra passes - 1) emitting inner symbols 2) emitting types that are used
but unprovided.
Inner symbols emit is needed because TS has no inner
classes/enums/interfaces, so they have to be emitted as separate
namespaces.
With
https://github.com/angular/clutz/commit/b1442f1af513524809dffac743edc2630a23c678
we improved the inner emit to emit more.
However, this means in some cases inner symbol emit and unprovided emit
were emitting the same type. This change makes sure that unprovided emit
doesn't visit inner symbols.

Fix double emit for inner and unprovided types.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java

Original CL description: Make union types more efficient by eliminating unnecessary redundancy.  This change modifies union types to always leave structural subtypes in the union.  This can result in additional types errors if the previously collapsed type provides a definition for a property or if the collapsed type was `@struct` (as any `@struct` member of the union causes the member to be considered `@struct`).
This should fix the broken CI.

Sync a change from google3.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/ProgramSubject.java
src/test/java/com/google/javascript/clutz/general_with_platform.d.ts

1) w3c_file api was split which moved things around in
general_with_platform.d.ts.
2) Truth Subjects from no-arg check() was migrated to the overload that
accepts descrition.
3) collectTypedefs ignores symbols from TYPESCRIPT_LIB_D_TS and CLOSURE_EXTERNS_NOT_USED_IN_TYPESCRIPT

Upgrade clutz with some changes made internally.

---

src/test/java/com/google/javascript/clutz/partial/missing_base_union.d.ts
src/test/java/com/google/javascript/clutz/partial/missing_base_union.js

In case of interfaces that extend another one beyond the scope of
visibility of partial clutz, it appears that unions with |null or
|undefined are collapsed by Closure.
This adds a test exemplifying the failure.

Add example of union of partially visible interface collapsing.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java

In the past closure had getAlternates and
getAlternatesWithoutStructuralTyping. Since
https://github.com/angular/clutz/commit/733783dc299805a963272d4d77bf11b12668fad4
there is only a single method, so this comment is not relevant.

Remove no longer relevant comment.

---

src/test/java/com/google/javascript/clutz/ProgramSubject.java

Original changelist description:
```
Instead of calling Subject.actual(), store the actual value in a field, and read that.
actual() is being removed.
```

Sync an internal change.

---

src/main/java/com/google/javascript/gents/TypeAnnotationPass.java
src/test/java/com/google/javascript/gents/singleTests/functions.js
src/test/java/com/google/javascript/gents/singleTests/functions.ts

/**
* @param {boolean=} a
*/
function f(a = undefined)
should translate to
function f(a: boolean|undefined = undefined)
fixes #631, fixes #629

Handle optional parameters with a default value of undefined.

---

src/main/java/com/google/javascript/gents/CommentLinkingPass.java
src/test/java/com/google/javascript/gents/singleTests/inline_comments.js
src/test/java/com/google/javascript/gents/singleTests/inline_comments.ts

Previously inline comments were attached to the next node after the
comment, but that doesn't work in cases where a comment is after an
argument, but before the comma separating arguments.
fixes #646

Make sure to associate comments with the correct function args.

---

src/main/java/com/google/javascript/gents/CollectModuleMetadata.java
src/main/java/com/google/javascript/gents/ModuleConversionPass.java
src/test/java/com/google/javascript/gents/multiTests/jslib_imports/export_mixed_default_namespaces_keep.js
src/test/java/com/google/javascript/gents/multiTests/jslib_imports/import_mixed_default_namespaces.js
src/test/java/com/google/javascript/gents/multiTests/jslib_imports/import_mixed_default_namespaces.ts

Previously, gents assumed that each file only had one namespace that it
exported, so when checking if an import was of a default export or not,
it resolved to whether whatever the first exported namespace in the file
was.  This change makes it so each namespace that's exported is tracked
separately.

Fix imports from files with multiple namespaces.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java

Previously, the two were synonims, but Closure removed
FUNCTION_INSTANCE_TYPE from upstream.
U2U stands for unknown-to-unknown.

Rename FUNCTION_INSTANCE_TYPE to U2U_CONSTRUCTOR_TYPE.

---

src/main/java/com/google/javascript/clutz/AliasMapBuilder.java
src/test/java/com/google/javascript/clutz/partial/extern_reexport.d.ts
src/test/java/com/google/javascript/clutz/partial/extern_reexport.js

For example `exports.x = someExtern.x`, prior to this clutz emitted
absolute junk using 'null.x' as a symbol.
Note, that this further exposes an issue with deeper reexports
'someExtern.deeper.y', which will be fixed in subsequent PR.

Fix reexports in the case where RHS comes from an externs.

---

src/main/java/com/google/javascript/gents/TypeAnnotationPass.java
src/test/java/com/google/javascript/clutz/general_with_platform.d.ts

- Rename Node from ELLIPSIS to ITER_REST.
The two are synonyms. This matches change made to the closure AST so
that ELLIPSIS can be deleted.
- add new type KeyframeEffectReadOnly to platform externs.

Upstream two small closure changes.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/test/java/com/google/javascript/clutz/nested_enums.d.ts
src/test/java/com/google/javascript/clutz/nested_enums.js
src/test/java/com/google/javascript/clutz/static_enum.d.ts

This is my attempt at making Clutz preserve comments from JS on enums and enum values.
This should fix #892

(Fix #892) Write comments from enum types on generated .d.ts symbols

---

src/main/java/com/google/javascript/gents/CollectModuleMetadata.java

This is a purely stylistic change, matchesQualified behaves like matches
when passed a string without using dot accessors inside like 'a.b.c'.

Replace calls to matchesQualified with just matches.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java
src/main/java/com/google/javascript/clutz/ImportBasedMapBuilder.java
src/main/java/com/google/javascript/clutz/ImportRenameMapBuilder.java
src/main/java/com/google/javascript/clutz/LegacyNamespaceReexportMapBuilder.java
src/test/java/com/google/javascript/clutz/testdata/partialCrossModuleTypeImports/goog_legacy_namespace_exporter.d.ts

Replaces all HashMap/Set with LinkedHashMap/Set which guarantee
iteration order matches the input order.
Replace some Collections.toMap calls with for loops, because I couldn't
find a Collections.toLinkedMap calls.
Replace Collections.emptyMap calls with LinkedHashMap constructors.
Fixes one test, which has different emit order now.

Fix determinism in Clutz output.

---

src/main/java/com/google/javascript/clutz/DeclarationGenerator.java

Tested:
there is no test for that edge case as I couldn't force it on clean unit test
tested building some internal Google projects

Handle edge case when node might be null when emitting 'generated from' comment.

---

src/test/java/com/google/javascript/clutz/testdata/partial/enum_alias.d.ts
src/test/java/com/google/javascript/clutz/testdata/partial/enum_alias.js

The behavior changed with a closure change in March. The test is still
broken but in a different way.

Revert back the enum alias test.

---

src/main/java/com/google/javascript/clutz/Options.java
src/test/java/com/google/javascript/clutz/OptionsTest.java

This is no longer needed and it was never really used. We use depgraphs
to get the info of whether something was a goog.module or goog.provide.

Remove googProvides flag.

---

src/main/java/com/google/javascript/clutz/Depgraph.java

If an upstream build rule produces no source, then it's possible to have
an empty depgraph that is not malformed.

allow empty depgraphs

---

src/test/java/com/google/javascript/clutz/testdata/partial/global_generic_type.d.ts
src/test/java/com/google/javascript/clutz/testdata/partial/global_generic_type.js

A Closure Compiler change will begin special casing 'global' as it is native to Node environments. This causes issues when trying to goog.provide it. See also discussion on Google internal
http://cl/270391864.

Rename goog.provide from 'global' to 'globalNs'

---

.circleci/config.yml
build.gradle

Sonatype returns too many 404s for this to be reliable. In the future
github clutz/gents will test only against released closure versions, and
changes will be made internally against head.

Remove JSCompiler snapshot testing from CircleCI and builds.

---

src/test/java/com/google/javascript/clutz/testdata/partial/goog_module_get.d.ts
src/test/java/com/google/javascript/clutz/testdata/partial/goog_module_get.js

The destructuring pattern this test is using is banned in regular compiler invocations, but until an upcoming Closure Compiler change, is allowed in Clutz invocations. [example](https://closure-compiler-debugger.appspot.com/#input0%3Dgoog.provide('a')%253B%26input1%3Dgoog.scope(function()%2520%257B%250A%2520%2520const%2520%257Bb%257D%2520%253D%2520goog.module.get('a')%253B%250A%257D)%253B%26conformanceConfig%26externs%26refasterjs-template%26CHECK_TYPES%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue)
Also adds a regression test for when the right-hand side of a goog.provide assignment uses a goog.module.get. I ran into this case while testing a Closure Compiler change.

Remove destructuring to fix JSC_GOOG_SCOPE_NON_ALIAS_LOCAL

---

src/main/java/com/google/javascript/clutz/ClutzErrorManager.java
src/main/java/com/google/javascript/clutz/Options.java
src/test/java/com/google/javascript/clutz/testdata/all_optional_type.d.ts
src/test/java/com/google/javascript/clutz/testdata/general_with_platform.d.ts
src/test/java/com/google/javascript/clutz/testdata/partial/missing_base_union.d.ts
src/test/java/com/google/javascript/clutz/testdata/partial/missing_base_union.js
src/test/java/com/google/javascript/gents/singleTests/comments.ts
src/test/java/com/google/javascript/gents/singleTests/functions.js
src/test/java/com/google/javascript/gents/singleTests/functions.ts

- closure has fixed union collapse at head, which required undating some
failing goldens.
- new extern changes.
- replacing .description with getDescription.
- Better Java types for Options.java.
- new test for gents with destructuring arguments.
- clang-format reformating for a gents test.

Upstreaming 6 minor internal changes.
